"""Adicionando oficina_dia_id e sucesso em Checkin

Revision ID: 00a3ee58ef28
Revises: 6b97898b7ba8
Create Date: 2025-02-21 00:40:18.094963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00a3ee58ef28'
down_revision = '6b97898b7ba8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('cliente')
    #op.drop_table('evento')
    with op.batch_alter_table('inscricao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checkin_attempts', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['qr_code_token'])

    with op.batch_alter_table('ministrante', schema=None) as batch_op:
        batch_op.drop_constraint('ministrante_cliente_id_fkey', type_='foreignkey')
        batch_op.drop_column('cliente_id')

    with op.batch_alter_table('oficina', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opcoes_checkin', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('palavra_correta', sa.String(length=50), nullable=True))
        batch_op.drop_constraint('oficina_evento_id_fkey', type_='foreignkey')
        batch_op.drop_column('evento_id')

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint('usuario_cliente_id_fkey', type_='foreignkey')
        batch_op.drop_column('cliente_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cliente_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('usuario_cliente_id_fkey', 'cliente', ['cliente_id'], ['id'])

    with op.batch_alter_table('oficina', schema=None) as batch_op:
        batch_op.add_column(sa.Column('evento_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('oficina_evento_id_fkey', 'evento', ['evento_id'], ['id'])
        batch_op.drop_column('palavra_correta')
        batch_op.drop_column('opcoes_checkin')

    with op.batch_alter_table('ministrante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cliente_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('ministrante_cliente_id_fkey', 'cliente', ['cliente_id'], ['id'])

    with op.batch_alter_table('inscricao', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('checkin_attempts')

    op.create_table('evento',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('data_inicio', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('data_fim', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('cliente_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name='evento_cliente_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='evento_pkey')
    )
    op.create_table('cliente',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('cnpj', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=150), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('senha', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='cliente_pkey'),
    sa.UniqueConstraint('cnpj', name='cliente_cnpj_key'),
    sa.UniqueConstraint('email', name='cliente_email_key')
    )
    # ### end Alembic commands ###
