"""Recreating migrations

Revision ID: 01a981839e0c
Revises: 
Create Date: 2025-02-25 15:51:50.196508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01a981839e0c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('formularios', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'cliente', ['cliente_id'], ['id'])

    with op.batch_alter_table('inscricao', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'cliente', ['cliente_id'], ['id'])

    with op.batch_alter_table('link_cadastro', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'cliente', ['cliente_id'], ['id'])

    with op.batch_alter_table('ministrante', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'cliente', ['cliente_id'], ['id'])

    with op.batch_alter_table('oficina', schema=None) as batch_op:
        batch_op.alter_column('cliente_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'cliente', ['cliente_id'], ['id'])

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'cliente', ['cliente_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('oficina', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('cliente_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('ministrante', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('link_cadastro', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('inscricao', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('formularios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
