"""Recriando estrutura do banco

Revision ID: 050b2313a66b
Revises: 211c72b36c3e
Create Date: 2025-03-25 00:27:37.619055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '050b2313a66b'
down_revision = '211c72b36c3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('texto_personalizado', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_column('texto_personalizado')

    # ### end Alembic commands ###
