"""add MFA fields to usuario

Revision ID: 059afbcdc79f
Revises: 7a34e60bbcaf
Create Date: 2025-06-20 12:25:53.857205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '059afbcdc79f'
down_revision = '7a34e60bbcaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('locator', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('access_code', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('note', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(
            'uq_review_locator',
            ['locator']
        )

    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.alter_column('locator',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mfa_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('mfa_secret', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('mfa_secret')
        batch_op.drop_column('mfa_enabled')

    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.alter_column('locator',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint(
            'uq_review_locator',
            type_='unique'
        )
        batch_op.drop_column('note')
        batch_op.drop_column('access_code')
        batch_op.drop_column('locator')

    # ### end Alembic commands ###
