"""empty message

Revision ID: 06d86eb40a74
Revises: 6d9072416e97
Create Date: 2025-03-15 10:48:27.365894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06d86eb40a74'
down_revision = '6d9072416e97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'evento',
        sa.Column(
            'inscricao_gratuita',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false()
        )
    )
    # Se desejar remover o default após a atualização dos registros, faça:
    op.alter_column('evento', 'inscricao_gratuita', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_column('evento', 'inscricao_gratuita')

    # ### end Alembic commands ###
