"""add material and polo models

Revision ID: 085998713db1
Revises: 9fade0f7ad63
Create Date: 2025-09-01 21:13:01.599898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '085998713db1'
down_revision = '9fade0f7ad63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('polo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('endereco', sa.String(length=500), nullable=True),
    sa.Column('responsavel', sa.String(length=255), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('fk_polo_cliente_id_cliente')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_polo'))
    )
    op.create_table('material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('unidade', sa.String(length=50), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('quantidade_inicial', sa.Integer(), nullable=False),
    sa.Column('quantidade_atual', sa.Integer(), nullable=False),
    sa.Column('quantidade_consumida', sa.Integer(), nullable=False),
    sa.Column('quantidade_minima', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('polo_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('fk_material_cliente_id_cliente')),
    sa.ForeignKeyConstraint(['polo_id'], ['polo.id'], name=op.f('fk_material_polo_id_polo')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_material'))
    )
    op.create_table('monitor_polo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monitor_id', sa.Integer(), nullable=False),
    sa.Column('polo_id', sa.Integer(), nullable=False),
    sa.Column('data_atribuicao', sa.DateTime(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitor.id'], name=op.f('fk_monitor_polo_monitor_id_monitor')),
    sa.ForeignKeyConstraint(['polo_id'], ['polo.id'], name=op.f('fk_monitor_polo_polo_id_polo')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monitor_polo'))
    )
    op.create_table('movimentacao_material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('data_movimentacao', sa.DateTime(), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('monitor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], name=op.f('fk_movimentacao_material_material_id_material')),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitor.id'], name=op.f('fk_movimentacao_material_monitor_id_monitor')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_movimentacao_material_usuario_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movimentacao_material'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movimentacao_material')
    op.drop_table('monitor_polo')
    op.drop_table('material')
    op.drop_table('polo')
    # ### end Alembic commands ###
