"""Migração inicial

Revision ID: 088514646ca3
Revises: 
Create Date: 2025-03-18 14:23:56.369725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '088514646ca3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('professor')
    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.alter_column('capacidade_padrao',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('requer_aprovacao',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('publico',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.alter_column('publico',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('requer_aprovacao',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('capacidade_padrao',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.create_table('professor',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('senha', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('cpf', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('formacao', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='professor_pkey'),
    sa.UniqueConstraint('cpf', name='professor_cpf_key'),
    sa.UniqueConstraint('email', name='professor_email_key')
    )
    # ### end Alembic commands ###
