"""empty message

Revision ID: 0aedd9fbed41
Revises: 85f76d806b22
Create Date: 2025-09-30 12:18:55.045615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aedd9fbed41'
down_revision = '85f76d806b22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificado_revisor', schema=None) as batch_op:
        batch_op.drop_index('ix_certificado_revisor_liberado')
        batch_op.drop_index('ix_certificado_revisor_revisor_cliente')

    with op.batch_alter_table('certificado_revisor_config', schema=None) as batch_op:
        batch_op.drop_index('ix_certificado_revisor_config_cliente_evento')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificado_revisor_config', schema=None) as batch_op:
        batch_op.create_index('ix_certificado_revisor_config_cliente_evento', ['cliente_id', 'evento_id'], unique=False)

    with op.batch_alter_table('certificado_revisor', schema=None) as batch_op:
        batch_op.create_index('ix_certificado_revisor_revisor_cliente', ['revisor_id', 'cliente_id'], unique=False)
        batch_op.create_index('ix_certificado_revisor_liberado', ['liberado'], unique=False)

    # ### end Alembic commands ###
