"""Recriando migrações

Revision ID: 0cb707093902
Revises: 
Create Date: 2025-02-21 18:33:25.006884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cb707093902'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('habilitar_certificado_individual', sa.Boolean(), nullable=True))

    with op.batch_alter_table('oficina', schema=None) as batch_op:
        batch_op.add_column(sa.Column('palavra_correta', sa.String(length=50), nullable=True))
        batch_op.alter_column('opcoes_checkin',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True,
               existing_server_default=sa.text("''::text"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oficina', schema=None) as batch_op:
        batch_op.alter_column('opcoes_checkin',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("''::text"))
        batch_op.drop_column('palavra_correta')

    with op.batch_alter_table('configuracao', schema=None) as batch_op:
        batch_op.drop_column('habilitar_certificado_individual')

    # ### end Alembic commands ###
