"""empty message

Revision ID: 0e3ffde07361
Revises: c20b45a05c90
Create Date: 2025-09-19 17:54:26.522796

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0e3ffde07361'
down_revision = 'c20b45a05c90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orcamento_cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor_total_disponivel', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('valor_custeio_disponivel', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('valor_capital_disponivel', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('valor_alerta_total', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('valor_alerta_custeio', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('valor_alerta_capital', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('ano_orcamento', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('mes_inicio', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('mes_fim', sa.Integer(), nullable=False))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index('ix_orcamento_cliente_ano_mes')
        batch_op.drop_index('ix_orcamento_cliente_cliente_id')
        batch_op.drop_constraint('uq_orcamento_cliente_periodo', type_='unique')
        batch_op.drop_constraint('fk_orcamento_cliente_cliente_id_cliente', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_orcamento_cliente_cliente_id_cliente'), 'cliente', ['cliente_id'], ['id'])
        batch_op.drop_column('valor_orcamento_custeio')
        batch_op.drop_column('alerta_ativo_capital')
        batch_op.drop_column('valor_orcamento_capital')
        batch_op.drop_column('alerta_ativo_custeio')
        batch_op.drop_column('percentual_alerta_capital')
        batch_op.drop_column('valor_gasto_custeio')
        batch_op.drop_column('percentual_alerta_custeio')
        batch_op.drop_column('mes')
        batch_op.drop_column('ano')
        batch_op.drop_column('valor_gasto_capital')
        batch_op.drop_column('observacoes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orcamento_cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observacoes', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('valor_gasto_capital', sa.NUMERIC(precision=15, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('ano', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('mes', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('percentual_alerta_custeio', sa.INTEGER(), server_default=sa.text('80'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('valor_gasto_custeio', sa.NUMERIC(precision=15, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('percentual_alerta_capital', sa.INTEGER(), server_default=sa.text('80'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('alerta_ativo_custeio', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('valor_orcamento_capital', sa.NUMERIC(precision=15, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('alerta_ativo_capital', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('valor_orcamento_custeio', sa.NUMERIC(precision=15, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_orcamento_cliente_cliente_id_cliente'), type_='foreignkey')
        batch_op.create_foreign_key('fk_orcamento_cliente_cliente_id_cliente', 'cliente', ['cliente_id'], ['id'], ondelete='CASCADE')
        batch_op.create_unique_constraint('uq_orcamento_cliente_periodo', ['cliente_id', 'ano', 'mes'])
        batch_op.create_index('ix_orcamento_cliente_cliente_id', ['cliente_id'], unique=False)
        batch_op.create_index('ix_orcamento_cliente_ano_mes', ['ano', 'mes'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_column('mes_fim')
        batch_op.drop_column('mes_inicio')
        batch_op.drop_column('ano_orcamento')
        batch_op.drop_column('valor_alerta_capital')
        batch_op.drop_column('valor_alerta_custeio')
        batch_op.drop_column('valor_alerta_total')
        batch_op.drop_column('valor_capital_disponivel')
        batch_op.drop_column('valor_custeio_disponivel')
        batch_op.drop_column('valor_total_disponivel')

    # ### end Alembic commands ###
