"""initial

Revision ID: 12507db40862
Revises: 
Create Date: 2025-04-11 12:10:03.207988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12507db40862'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscricao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_pagamento', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscricao', schema=None) as batch_op:
        batch_op.drop_column('status_pagamento')

    # ### end Alembic commands ###
