"""empty message

Revision ID: 13fb46fe90bf
Revises: 0daa64767343
Create Date: 2025-08-27 13:02:35.498173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13fb46fe90bf'
down_revision = '0daa64767343'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if not inspector.has_table("notificacao_agendamento"):
        op.create_table('notificacao_agendamento',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('agendamento_id', sa.Integer(), nullable=False),
        sa.Column('remetente_id', sa.Integer(), nullable=False),
        sa.Column('destinatario_id', sa.Integer(), nullable=False),
        sa.Column('tipo', sa.String(length=50), nullable=False),
        sa.Column('titulo', sa.String(length=200), nullable=False),
        sa.Column('mensagem', sa.Text(), nullable=False),
        sa.Column('lida', sa.Boolean(), nullable=True),
        sa.Column('respondida', sa.Boolean(), nullable=True),
        sa.Column('data_criacao', sa.DateTime(), nullable=True),
        sa.Column('data_leitura', sa.DateTime(), nullable=True),
        sa.Column('data_resposta', sa.DateTime(), nullable=True),
        sa.Column('resposta', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['agendamento_id'], ['agendamento_visita.id'], name=op.f('fk_notificacao_agendamento_agendamento_id_agendamento_visita')),
        sa.ForeignKeyConstraint(['destinatario_id'], ['usuario.id'], name=op.f('fk_notificacao_agendamento_destinatario_id_usuario')),
        sa.ForeignKeyConstraint(['remetente_id'], ['usuario.id'], name=op.f('fk_notificacao_agendamento_remetente_id_usuario')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_notificacao_agendamento'))
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notificacao_agendamento')
    # ### end Alembic commands ###
