"""Add InscricaoEvento model

Revision ID: 161829795685
Revises: 35d2a2777aea
Create Date: 2025-04-02 16:07:13.918739

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '161829795685'
down_revision = '35d2a2777aea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamento_visita', schema=None) as batch_op:
        batch_op.drop_column('escola_codigo_inep')
        batch_op.drop_column('turma')
        batch_op.drop_column('data_cancelamento')

    with op.batch_alter_table('inscricao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_inscricao_evento_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'evento_inscricao_tipo', ['tipo_inscricao_evento_id'], ['id'])

    with op.batch_alter_table('sala_visitacao', schema=None) as batch_op:
        batch_op.drop_column('nome')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sala_visitacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False))

    with op.batch_alter_table('inscricao', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tipo_inscricao_evento_id')

    with op.batch_alter_table('agendamento_visita', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_cancelamento', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('turma', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('escola_codigo_inep', sa.VARCHAR(length=20), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
