"""empty message

Revision ID: 17ea7e0df270
Revises: 2399efae0e12
Create Date: 2025-06-16 11:15:06.686439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17ea7e0df270'
down_revision = '2399efae0e12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracao_cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mostrar_taxa', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracao_cliente', schema=None) as batch_op:
        batch_op.drop_column('mostrar_taxa')

    # ### end Alembic commands ###
