"""Add categoria_barema and teste_barema tables

Revision ID: 1cc208dfc5fa
Revises: 3fd26a27c462
Create Date: 2025-09-17 15:40:37.526929

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1cc208dfc5fa'
down_revision = '3fd26a27c462'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teste_barema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barema_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('pontuacoes', sa.JSON(), nullable=False),
    sa.Column('total_pontos', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['barema_id'], ['categoria_barema.id'], name=op.f('fk_teste_barema_barema_id_categoria_barema')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_teste_barema_usuario_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teste_barema'))
    )
    with op.batch_alter_table('monitor', schema=None) as batch_op:
        batch_op.drop_column('disponibilidade_detalhada')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disponibilidade_detalhada', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))

    op.drop_table('teste_barema')
    # ### end Alembic commands ###
