"""add protected field to campos_formulario

Revision ID: 1e6c5277571b
Revises: 2f01fce91968
Create Date: 2025-08-26 15:54:53.269402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e6c5277571b'
down_revision = '2f01fce91968'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campos_formulario', schema=None) as batch_op:
        existing_cols = {col['name'] for col in inspector.get_columns("campos_formulario")}
        existing_fks = {fk['name'] for fk in inspector.get_foreign_keys("campos_formulario")}
        if "protegido" not in existing_cols:
            batch_op.add_column(sa.Column('protegido', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campos_formulario', schema=None) as batch_op:
        existing_cols = {col['name'] for col in inspector.get_columns("campos_formulario")}
        existing_fks = {fk['name'] for fk in inspector.get_foreign_keys("campos_formulario")}
        batch_op.drop_column('protegido')

    # ### end Alembic commands ###
