"""Adicionando campo habilitar_feedback na tabela Configuracao relatorio ministranteATUALIZANDOCOMERRdeppO

Revision ID: 1fd10484cc3a
Revises: e1df3e7726a0
Create Date: 2025-02-06 18:53:34.704157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fd10484cc3a'
down_revision = 'e1df3e7726a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
