"""adiciona campo texto_personalizado

Revision ID: 211c72b36c3e
Revises: 8de5ceef817a
Create Date: 2025-03-24 15:23:11.140123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '211c72b36c3e'
down_revision = '8de5ceef817a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('texto_personalizado', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_column('texto_personalizado')

    # ### end Alembic commands ###
