"""add taxa_fixa_inscricao em Configuracao

Revision ID: 2744d4add4b2
Revises: ced4f6bf8596
Create Date: 2025-04-23 02:15:26.161314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2744d4add4b2'
down_revision = 'ced4f6bf8596'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('taxa_fixa_inscricao', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracao', schema=None) as batch_op:
        batch_op.drop_column('taxa_fixa_inscricao')

    # ### end Alembic commands ###
