"""add_security_fields_to_documento_fiscal

Revision ID: 27f85c2ac4a0
Revises: e496c12490c7
Create Date: 2025-09-17 14:59:20.506543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27f85c2ac4a0'
down_revision = 'e496c12490c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_compra', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('fornecedor', sa.String(length=255), nullable=False),
    sa.Column('cnpj_fornecedor', sa.String(length=18), nullable=True),
    sa.Column('endereco_fornecedor', sa.Text(), nullable=True),
    sa.Column('telefone_fornecedor', sa.String(length=20), nullable=True),
    sa.Column('email_fornecedor', sa.String(length=255), nullable=True),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.Column('valor_frete', sa.Float(), nullable=True),
    sa.Column('valor_desconto', sa.Float(), nullable=True),
    sa.Column('valor_impostos', sa.Float(), nullable=True),
    sa.Column('data_compra', sa.DateTime(), nullable=False),
    sa.Column('data_entrega_prevista', sa.DateTime(), nullable=True),
    sa.Column('data_entrega_realizada', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('justificativa', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('polo_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('fk_compra_cliente_id_cliente')),
    sa.ForeignKeyConstraint(['polo_id'], ['polo.id'], name=op.f('fk_compra_polo_id_polo')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_compra_usuario_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compra')),
    sa.UniqueConstraint('numero_compra', name=op.f('uq_compra_numero_compra'))
    )
    op.create_table('prestacao_contas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_prestacao', sa.String(length=50), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_fim', sa.DateTime(), nullable=False),
    sa.Column('valor_total_compras', sa.Float(), nullable=False),
    sa.Column('valor_total_documentos', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('observacoes_aprovacao', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('data_envio', sa.DateTime(), nullable=True),
    sa.Column('data_aprovacao', sa.DateTime(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('usuario_aprovacao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('fk_prestacao_contas_cliente_id_cliente')),
    sa.ForeignKeyConstraint(['usuario_aprovacao_id'], ['usuario.id'], name=op.f('fk_prestacao_contas_usuario_aprovacao_id_usuario')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_prestacao_contas_usuario_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prestacao_contas')),
    sa.UniqueConstraint('numero_prestacao', name=op.f('uq_prestacao_contas_numero_prestacao'))
    )
    op.create_table('relatorio_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('filtros', sa.Text(), nullable=True),
    sa.Column('campos_exibir', sa.Text(), nullable=True),
    sa.Column('ordenacao', sa.String(length=100), nullable=True),
    sa.Column('ordem_crescente', sa.Boolean(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('publico', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('fk_relatorio_compra_cliente_id_cliente')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_relatorio_compra_usuario_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_relatorio_compra'))
    )
    op.create_table('documento_fiscal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_documento', sa.String(length=50), nullable=False),
    sa.Column('numero_documento', sa.String(length=100), nullable=True),
    sa.Column('serie_documento', sa.String(length=20), nullable=True),
    sa.Column('chave_acesso', sa.String(length=44), nullable=True),
    sa.Column('nome_arquivo', sa.String(length=255), nullable=False),
    sa.Column('nome_arquivo_seguro', sa.String(length=255), nullable=True),
    sa.Column('caminho_arquivo', sa.String(length=500), nullable=False),
    sa.Column('tamanho_arquivo', sa.Integer(), nullable=True),
    sa.Column('tipo_mime', sa.String(length=100), nullable=True),
    sa.Column('hash_arquivo', sa.String(length=64), nullable=True),
    sa.Column('validacao_resultado', sa.Text(), nullable=True),
    sa.Column('scan_seguranca', sa.Text(), nullable=True),
    sa.Column('data_emissao', sa.DateTime(), nullable=True),
    sa.Column('valor_documento', sa.Float(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('compra_id', sa.Integer(), nullable=False),
    sa.Column('usuario_upload_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['compra_id'], ['compra.id'], name=op.f('fk_documento_fiscal_compra_id_compra')),
    sa.ForeignKeyConstraint(['usuario_upload_id'], ['usuario.id'], name=op.f('fk_documento_fiscal_usuario_upload_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documento_fiscal'))
    )
    op.create_table('item_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('unidade', sa.String(length=50), nullable=False),
    sa.Column('preco_unitario', sa.Float(), nullable=False),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('compra_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['compra_id'], ['compra.id'], name=op.f('fk_item_compra_compra_id_compra')),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], name=op.f('fk_item_compra_material_id_material')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_compra'))
    )
    op.create_table('prestacao_compra',
    sa.Column('prestacao_id', sa.Integer(), nullable=False),
    sa.Column('compra_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['compra_id'], ['compra.id'], name=op.f('fk_prestacao_compra_compra_id_compra')),
    sa.ForeignKeyConstraint(['prestacao_id'], ['prestacao_contas.id'], name=op.f('fk_prestacao_compra_prestacao_id_prestacao_contas')),
    sa.PrimaryKeyConstraint('prestacao_id', 'compra_id', name=op.f('pk_prestacao_compra'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prestacao_compra')
    op.drop_table('item_compra')
    op.drop_table('documento_fiscal')
    op.drop_table('relatorio_compra')
    op.drop_table('prestacao_contas')
    op.drop_table('compra')
    # ### end Alembic commands ###
