"""habilitar submissao de trabalhos

Revision ID: 284d77f90e08
Revises: e8249eb9ca71
Create Date: 2025-04-08 17:56:24.671741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '284d77f90e08'
down_revision = 'e8249eb9ca71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracao_cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('habilitar_submissao_trabalhos', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracao_cliente', schema=None) as batch_op:
        batch_op.drop_column('habilitar_submissao_trabalhos')

    # ### end Alembic commands ###
