"""empty message

Revision ID: 2ab96a295f6b
Revises: 8d869405844d
Create Date: 2025-09-23 12:29:54.082694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ab96a295f6b'
down_revision = '8d869405844d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submissao_aberta', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.drop_column('submissao_aberta')

    # ### end Alembic commands ###
