"""empty message

Revision ID: 2ff567091303
Revises: 2b39319b5045
Create Date: 2025-07-10 22:45:14.417237

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2ff567091303'
down_revision = '2b39319b5045'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campos_personalizados_cadastro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('evento_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_campos_personalizados_cadastro_evento_id_evento'), 'evento', ['evento_id'], ['id'])

    with op.batch_alter_table('configuracao_evento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permitir_checkin_global', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('habilitar_certificado_individual', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('habilitar_qrcode_evento_credenciamento', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('habilitar_submissao_trabalhos', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('taxa_diferenciada', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('allowed_file_types', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('review_model', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('num_revisores_min', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('num_revisores_max', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('prazo_parecer_dias', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('limite_eventos', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('limite_inscritos', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('limite_formularios', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('limite_revisores', sa.Integer(), nullable=True))
        batch_op.drop_constraint('uq_configuracao_evento_evento_id', type_='unique')
        batch_op.drop_column('permitir_checkin')
        batch_op.drop_column('habilitar_certificado')
        batch_op.drop_column('habilitar_qrcode_credenciamento')

    with op.batch_alter_table('reviewer_application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('evento_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('numero_revisores', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('prazo_revisao', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('modelo_blind', sa.String(length=20), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_reviewer_application_evento_id_evento'), 'evento', ['evento_id'], ['id'])

    with op.batch_alter_table('revisao_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permitir_checkin_global', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('habilitar_feedback', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('habilitar_certificado_individual', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('habilitar_qrcode_evento_credenciamento', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('habilitar_submissao_trabalhos', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('mostrar_taxa', sa.Boolean(), nullable=True))
        batch_op.drop_column('modelo_blind')
        batch_op.drop_column('numero_revisores')
        batch_op.drop_column('prazo_revisao')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('revisao_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prazo_revisao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('numero_revisores', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('modelo_blind', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_column('mostrar_taxa')
        batch_op.drop_column('habilitar_submissao_trabalhos')
        batch_op.drop_column('habilitar_qrcode_evento_credenciamento')
        batch_op.drop_column('habilitar_certificado_individual')
        batch_op.drop_column('habilitar_feedback')
        batch_op.drop_column('permitir_checkin_global')

    with op.batch_alter_table('reviewer_application', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_reviewer_application_evento_id_evento'), type_='foreignkey')
        batch_op.drop_column('modelo_blind')
        batch_op.drop_column('prazo_revisao')
        batch_op.drop_column('numero_revisores')
        batch_op.drop_column('evento_id')

    with op.batch_alter_table('configuracao_evento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('habilitar_qrcode_credenciamento', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('habilitar_certificado', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('permitir_checkin', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('uq_configuracao_evento_evento_id', ['evento_id'])
        batch_op.drop_column('limite_revisores')
        batch_op.drop_column('limite_formularios')
        batch_op.drop_column('limite_inscritos')
        batch_op.drop_column('limite_eventos')
        batch_op.drop_column('prazo_parecer_dias')
        batch_op.drop_column('num_revisores_max')
        batch_op.drop_column('num_revisores_min')
        batch_op.drop_column('review_model')
        batch_op.drop_column('allowed_file_types')
        batch_op.drop_column('taxa_diferenciada')
        batch_op.drop_column('habilitar_submissao_trabalhos')
        batch_op.drop_column('habilitar_qrcode_evento_credenciamento')
        batch_op.drop_column('habilitar_certificado_individual')
        batch_op.drop_column('permitir_checkin_global')

    with op.batch_alter_table('campos_personalizados_cadastro', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_campos_personalizados_cadastro_evento_id_evento'), type_='foreignkey')
        batch_op.drop_column('evento_id')

    # ### end Alembic commands ###
