"""empty message

Revision ID: 3267ae82aadf
Revises: 03b7e3c050f6
Create Date: 2025-09-08 14:01:17.199525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3267ae82aadf'
down_revision = '03b7e3c050f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distribution_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=True),
    sa.Column('distribution_type', sa.String(length=20), nullable=False),
    sa.Column('total_works', sa.Integer(), nullable=False),
    sa.Column('total_reviewers', sa.Integer(), nullable=False),
    sa.Column('assignments_created', sa.Integer(), nullable=False),
    sa.Column('distribution_date', sa.DateTime(), nullable=False),
    sa.Column('distributed_by', sa.Integer(), nullable=True),
    sa.Column('filters_applied', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['distributed_by'], ['usuario.id'], name=op.f('fk_distribution_log_distributed_by_usuario')),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id'], name=op.f('fk_distribution_log_evento_id_evento')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_distribution_log'))
    )
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resposta_formulario_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('distribution_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('distribution_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('distributed_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.drop_constraint('fk_assignment_submission_id_submission', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_assignment_resposta_formulario_id_respostas_formulario'), 'respostas_formulario', ['resposta_formulario_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_assignment_distributed_by_usuario'), 'usuario', ['distributed_by'], ['id'])
        batch_op.drop_column('submission_id')

    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.alter_column('ativo',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('respostas_formulario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trabalho_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('evento_id', sa.Integer(), nullable=True))
        batch_op.alter_column('formulario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(batch_op.f('fk_respostas_formulario_evento_id_evento'), 'evento', ['evento_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_respostas_formulario_trabalho_id_submission'), 'submission', ['trabalho_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('respostas_formulario', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_respostas_formulario_trabalho_id_submission'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_respostas_formulario_evento_id_evento'), type_='foreignkey')
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('formulario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('evento_id')
        batch_op.drop_column('trabalho_id')

    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.alter_column('ativo',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submission_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_assignment_distributed_by_usuario'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_assignment_resposta_formulario_id_respostas_formulario'), type_='foreignkey')
        batch_op.create_foreign_key('fk_assignment_submission_id_submission', 'submission', ['submission_id'], ['id'])
        batch_op.drop_column('notes')
        batch_op.drop_column('distributed_by')
        batch_op.drop_column('distribution_date')
        batch_op.drop_column('distribution_type')
        batch_op.drop_column('resposta_formulario_id')

    op.drop_table('distribution_log')
    # ### end Alembic commands ###
