"""empty message

Revision ID: 32bf7215c932
Revises: ccf553bc9e47
Create Date: 2025-09-08 16:19:30.983084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32bf7215c932'
down_revision = 'ccf553bc9e47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitor_cadastro_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('fk_monitor_cadastro_link_cliente_id_cliente')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monitor_cadastro_link')),
    sa.UniqueConstraint('token', name=op.f('uq_monitor_cadastro_link_token'))
    )
    with op.batch_alter_table('agendamento_visita', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.String(length=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamento_visita', schema=None) as batch_op:
        batch_op.drop_column('estado')

    op.drop_table('monitor_cadastro_link')
    # ### end Alembic commands ###
