"""empty message

Revision ID: 3322b4d6a579
Revises: 997aabdf3c1d
Create Date: 2025-09-22 17:57:16.872757

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3322b4d6a579'
down_revision = '997aabdf3c1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracao_relatorio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('tipo', sa.Enum('ATIVIDADE', 'MENSAL', 'TRIMESTRAL', 'ANUAL', name='tiporelatorio'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('obrigatorio', sa.Boolean(), nullable=True),
    sa.Column('frequencia_dias', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('fk_configuracao_relatorio_cliente_id_cliente')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_configuracao_relatorio'))
    )
    op.create_table('campo_relatorio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.Enum('TEXTO', 'NUMERO', 'DATA', 'SELECAO', 'MULTIPLA_ESCOLHA', 'ARQUIVO', 'TEXTO_LONGO', name='tipocampo'), nullable=False),
    sa.Column('obrigatorio', sa.Boolean(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('opcoes', sa.Text(), nullable=True),
    sa.Column('placeholder', sa.String(length=200), nullable=True),
    sa.Column('validacao', sa.Text(), nullable=True),
    sa.Column('configuracao_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['configuracao_id'], ['configuracao_relatorio.id'], name=op.f('fk_campo_relatorio_configuracao_id_configuracao_relatorio')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campo_relatorio'))
    )
    op.create_table('categoria_barema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=255), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('criterios', sa.JSON(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id'], name=op.f('fk_categoria_barema_evento_id_evento')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categoria_barema'))
    )
    op.create_table('relatorio_formador_legacy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('configuracao_id', sa.Integer(), nullable=False),
    sa.Column('formador_id', sa.Integer(), nullable=False),
    sa.Column('atividade_id', sa.Integer(), nullable=True),
    sa.Column('periodo_inicio', sa.Date(), nullable=True),
    sa.Column('periodo_fim', sa.Date(), nullable=True),
    sa.Column('dados_relatorio', sa.JSON(), nullable=False),
    sa.Column('data_envio', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['atividade_id'], ['oficina.id'], name=op.f('fk_relatorio_formador_legacy_atividade_id_oficina')),
    sa.ForeignKeyConstraint(['configuracao_id'], ['configuracao_relatorio_formador.id'], name=op.f('fk_relatorio_formador_legacy_configuracao_id_configuracao_relatorio_formador')),
    sa.ForeignKeyConstraint(['formador_id'], ['ministrante.id'], name=op.f('fk_relatorio_formador_legacy_formador_id_ministrante')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_relatorio_formador_legacy'))
    )
    op.create_table('historico_relatorio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relatorio_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('usuario_tipo', sa.String(length=20), nullable=False),
    sa.Column('acao', sa.String(length=50), nullable=False),
    sa.Column('detalhes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['relatorio_id'], ['relatorio_formador.id'], name=op.f('fk_historico_relatorio_relatorio_id_relatorio_formador')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_historico_relatorio'))
    )
    op.create_table('resposta_campo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relatorio_id', sa.Integer(), nullable=False),
    sa.Column('campo_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Text(), nullable=True),
    sa.Column('arquivo_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campo_id'], ['campo_relatorio.id'], name=op.f('fk_resposta_campo_campo_id_campo_relatorio')),
    sa.ForeignKeyConstraint(['relatorio_id'], ['relatorio_formador.id'], name=op.f('fk_resposta_campo_relatorio_id_relatorio_formador')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resposta_campo'))
    )
    op.create_table('teste_barema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barema_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('pontuacoes', sa.JSON(), nullable=False),
    sa.Column('total_pontos', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['barema_id'], ['categoria_barema.id'], name=op.f('fk_teste_barema_barema_id_categoria_barema')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_teste_barema_usuario_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teste_barema'))
    )
    op.create_table('avaliacao_barema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trabalho_id', sa.Integer(), nullable=False),
    sa.Column('revisor_id', sa.Integer(), nullable=False),
    sa.Column('barema_id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=255), nullable=False),
    sa.Column('nota_final', sa.Float(), nullable=True),
    sa.Column('data_avaliacao', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['revisor_id'], ['usuario.id'], name=op.f('fk_avaliacao_barema_revisor_id_usuario')),
    sa.ForeignKeyConstraint(['trabalho_id'], ['submission.id'], name=op.f('fk_avaliacao_barema_trabalho_id_submission')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_avaliacao_barema'))
    )
    op.create_table('avaliacao_criterio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('avaliacao_id', sa.Integer(), nullable=False),
    sa.Column('criterio_id', sa.String(length=255), nullable=False),
    sa.Column('nota', sa.Float(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['avaliacao_id'], ['avaliacao_barema.id'], name=op.f('fk_avaliacao_criterio_avaliacao_id_avaliacao_barema')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_avaliacao_criterio'))
    )
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fornecedor', sa.String(length=255), nullable=True))

    with op.batch_alter_table('monitor_cadastro_link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usage_count', sa.Integer(), nullable=False))
        batch_op.drop_column('used')

    with op.batch_alter_table('relatorio_formador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oficina_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('observacoes_cliente', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('data_aprovacao', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('periodo_inicio',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('periodo_fim',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('data_envio',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_constraint('fk_relatorio_formador_atividade_id_oficina', type_='foreignkey')
        batch_op.drop_constraint('fk_relatorio_formador_configuracao_id_configuracao_rela_e433', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_relatorio_formador_oficina_id_oficina'), 'oficina', ['oficina_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_relatorio_formador_configuracao_id_configuracao_relatorio'), 'configuracao_relatorio', ['configuracao_id'], ['id'])
        batch_op.drop_column('atividade_id')
        batch_op.drop_column('dados_relatorio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relatorio_formador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dados_relatorio', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('atividade_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_relatorio_formador_configuracao_id_configuracao_relatorio'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_relatorio_formador_oficina_id_oficina'), type_='foreignkey')
        batch_op.create_foreign_key('fk_relatorio_formador_configuracao_id_configuracao_rela_e433', 'configuracao_relatorio_formador', ['configuracao_id'], ['id'])
        batch_op.create_foreign_key('fk_relatorio_formador_atividade_id_oficina', 'oficina', ['atividade_id'], ['id'])
        batch_op.alter_column('data_envio',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('periodo_fim',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('periodo_inicio',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('data_aprovacao')
        batch_op.drop_column('observacoes_cliente')
        batch_op.drop_column('status')
        batch_op.drop_column('oficina_id')

    with op.batch_alter_table('monitor_cadastro_link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('used', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('usage_count')

    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.drop_column('fornecedor')

    op.drop_table('avaliacao_criterio')
    op.drop_table('avaliacao_barema')
    op.drop_table('teste_barema')
    op.drop_table('resposta_campo')
    op.drop_table('historico_relatorio')
    op.drop_table('relatorio_formador_legacy')
    op.drop_table('categoria_barema')
    op.drop_table('campo_relatorio')
    op.drop_table('configuracao_relatorio')
    # ### end Alembic commands ###
