"""Add InscricaoEvento model

Revision ID: 35d2a2777aea
Revises: d696cddcb68a
Create Date: 2025-04-02 15:27:15.974365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35d2a2777aea'
down_revision = 'd696cddcb68a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscricao', schema=None) as batch_op:
        batch_op.drop_constraint('inscricao_tipo_inscricao_evento_id_fkey', type_='foreignkey')
        batch_op.drop_column('tipo_inscricao_evento_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscricao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_inscricao_evento_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('inscricao_tipo_inscricao_evento_id_fkey', 'evento_inscricao_tipo', ['tipo_inscricao_evento_id'], ['id'])

    # ### end Alembic commands ###
