"""Add FormadorCadastroLink model

Revision ID: 38ddeb14ceba
Revises: c7b47ee06203
Create Date: 2025-09-12 18:41:30.612335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38ddeb14ceba'
down_revision = 'c7b47ee06203'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formador_cadastro_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=36), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('fk_formador_cadastro_link_cliente_id_cliente')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_formador_cadastro_link')),
    sa.UniqueConstraint('token', name=op.f('uq_formador_cadastro_link_token'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('formador_cadastro_link')
    # ### end Alembic commands ###
