"""sua nova migração

Revision ID: 3e509fe31b3c
Revises: 32b5e5b73833
Create Date: 2025-06-26 17:16:35.167329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e509fe31b3c'
down_revision = '32b5e5b73833'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkin', schema=None) as batch_op:
        batch_op.drop_constraint('checkin_usuario_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_checkin_usuario_id_usuario'), 'usuario', ['usuario_id'], ['id'])

    with op.batch_alter_table('inscricao', schema=None) as batch_op:
        batch_op.drop_constraint('inscricao_usuario_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_inscricao_usuario_id_usuario'), 'usuario', ['usuario_id'], ['id'])

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint('review_reviewer_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_review_reviewer_id_usuario'), 'usuario', ['reviewer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_review_reviewer_id_usuario'), type_='foreignkey')
        batch_op.create_foreign_key('review_reviewer_id_fkey', 'usuario', ['reviewer_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('inscricao', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_inscricao_usuario_id_usuario'), type_='foreignkey')
        batch_op.create_foreign_key('inscricao_usuario_id_fkey', 'usuario', ['usuario_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('checkin', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_checkin_usuario_id_usuario'), type_='foreignkey')
        batch_op.create_foreign_key('checkin_usuario_id_fkey', 'usuario', ['usuario_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
