"""empty message

Revision ID: 3fd26a27c462
Revises: e496c12490c7
Create Date: 2025-09-17 10:51:08.027143

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3fd26a27c462'
down_revision = 'e496c12490c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material_disponivel', schema=None) as batch_op:
        batch_op.alter_column('disponivel_para_solicitacao',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('ativo',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index('ix_material_disponivel_cliente_id')
        batch_op.drop_constraint('fk_material_disponivel_cliente_id_cliente', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_material_disponivel_cliente_id_cliente'), 'cliente', ['cliente_id'], ['id'])

    with op.batch_alter_table('solicitacao_material_formador', schema=None) as batch_op:
        batch_op.alter_column('nome_material',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('unidade_medida',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('justificativa',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pendente'::character varying"))
        batch_op.alter_column('entregue',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('data_solicitacao',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index('ix_solicitacao_material_formador_cliente_id')
        batch_op.drop_index('ix_solicitacao_material_formador_data_solicitacao')
        batch_op.drop_index('ix_solicitacao_material_formador_formador_id')
        batch_op.drop_index('ix_solicitacao_material_formador_status')
        batch_op.drop_constraint('fk_solicitacao_material_formador_cliente_id_cliente', type_='foreignkey')
        batch_op.drop_constraint('fk_solicitacao_material_formador_formador_id_ministrante', type_='foreignkey')
        batch_op.drop_constraint('fk_solicitacao_material_formador_material_disponivel_id_materia', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_solicitacao_material_formador_formador_id_ministrante'), 'ministrante', ['formador_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_solicitacao_material_formador_cliente_id_cliente'), 'cliente', ['cliente_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_solicitacao_material_formador_material_disponivel_id_material_disponivel'), 'material_disponivel', ['material_disponivel_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacao_material_formador', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_solicitacao_material_formador_material_disponivel_id_material_disponivel'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_solicitacao_material_formador_cliente_id_cliente'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_solicitacao_material_formador_formador_id_ministrante'), type_='foreignkey')
        batch_op.create_foreign_key('fk_solicitacao_material_formador_material_disponivel_id_materia', 'material_disponivel', ['material_disponivel_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_solicitacao_material_formador_formador_id_ministrante', 'ministrante', ['formador_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_solicitacao_material_formador_cliente_id_cliente', 'cliente', ['cliente_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('ix_solicitacao_material_formador_status', ['status'], unique=False)
        batch_op.create_index('ix_solicitacao_material_formador_formador_id', ['formador_id'], unique=False)
        batch_op.create_index('ix_solicitacao_material_formador_data_solicitacao', ['data_solicitacao'], unique=False)
        batch_op.create_index('ix_solicitacao_material_formador_cliente_id', ['cliente_id'], unique=False)
        batch_op.alter_column('data_solicitacao',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('entregue',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pendente'::character varying"))
        batch_op.alter_column('justificativa',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('unidade_medida',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('nome_material',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               nullable=True)

    with op.batch_alter_table('material_disponivel', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_material_disponivel_cliente_id_cliente'), type_='foreignkey')
        batch_op.create_foreign_key('fk_material_disponivel_cliente_id_cliente', 'cliente', ['cliente_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('ix_material_disponivel_cliente_id', ['cliente_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('ativo',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('disponivel_para_solicitacao',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
