"""empty message

Revision ID: 3fd26a27c462
Revises: e496c12490c7
Create Date: 2025-09-17 10:51:08.027143

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3fd26a27c462'
down_revision = 'e496c12490c7'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material_disponivel', schema=None) as batch_op:
        existing_cols = {col['name'] for col in inspector.get_columns("material_disponivel")}
        fk_info = inspector.get_foreign_keys("material_disponivel")
        existing_fks = {fk['name'] for fk in fk_info}
        existing_indexes = {idx['name'] for idx in inspector.get_indexes("material_disponivel")}
        batch_op.alter_column('disponivel_para_solicitacao',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('ativo',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        if 'ix_material_disponivel_cliente_id' in existing_indexes:
            batch_op.drop_index('ix_material_disponivel_cliente_id')
        if 'fk_material_disponivel_cliente_id_cliente' in existing_fks:
            batch_op.drop_constraint('fk_material_disponivel_cliente_id_cliente', type_='foreignkey')
        if batch_op.f('fk_material_disponivel_cliente_id_cliente') not in existing_fks:
            batch_op.create_foreign_key(batch_op.f('fk_material_disponivel_cliente_id_cliente'), 'cliente', ['cliente_id'], ['id'])

    with op.batch_alter_table('solicitacao_material_formador', schema=None) as batch_op:
        existing_cols = {col['name'] for col in inspector.get_columns("solicitacao_material_formador")}
        fk_info = inspector.get_foreign_keys("solicitacao_material_formador")
        existing_fks = {fk['name'] for fk in fk_info}
        existing_indexes = {idx['name'] for idx in inspector.get_indexes("solicitacao_material_formador")}
        batch_op.alter_column('nome_material',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('unidade_medida',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('justificativa',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pendente'::character varying"))
        batch_op.alter_column('entregue',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('data_solicitacao',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        if 'ix_solicitacao_material_formador_cliente_id' in existing_indexes:
            batch_op.drop_index('ix_solicitacao_material_formador_cliente_id')
        if 'ix_solicitacao_material_formador_data_solicitacao' in existing_indexes:
            batch_op.drop_index('ix_solicitacao_material_formador_data_solicitacao')
        if 'ix_solicitacao_material_formador_formador_id' in existing_indexes:
            batch_op.drop_index('ix_solicitacao_material_formador_formador_id')
        if 'ix_solicitacao_material_formador_status' in existing_indexes:
            batch_op.drop_index('ix_solicitacao_material_formador_status')
        if 'fk_solicitacao_material_formador_cliente_id_cliente' in existing_fks:
            batch_op.drop_constraint('fk_solicitacao_material_formador_cliente_id_cliente', type_='foreignkey')
        if 'fk_solicitacao_material_formador_formador_id_ministrante' in existing_fks:
            batch_op.drop_constraint('fk_solicitacao_material_formador_formador_id_ministrante', type_='foreignkey')
        if 'fk_solicitacao_material_formador_material_disponivel_id_materia' in existing_fks:
            batch_op.drop_constraint('fk_solicitacao_material_formador_material_disponivel_id_materia', type_='foreignkey')
        has_fk_formador = any(
            fk.get("constrained_columns") == ["formador_id"]
            and fk.get("referred_table") == "ministrante"
            for fk in fk_info
        )
        has_fk_cliente = any(
            fk.get("constrained_columns") == ["cliente_id"]
            and fk.get("referred_table") == "cliente"
            for fk in fk_info
        )
        has_fk_material = any(
            fk.get("constrained_columns") == ["material_disponivel_id"]
            and fk.get("referred_table") == "material_disponivel"
            for fk in fk_info
        )

        if not has_fk_formador and batch_op.f('fk_solicitacao_material_formador_formador_id_ministrante') not in existing_fks:
            batch_op.create_foreign_key(batch_op.f('fk_solicitacao_material_formador_formador_id_ministrante'), 'ministrante', ['formador_id'], ['id'])
        if not has_fk_cliente and batch_op.f('fk_solicitacao_material_formador_cliente_id_cliente') not in existing_fks:
            batch_op.create_foreign_key(batch_op.f('fk_solicitacao_material_formador_cliente_id_cliente'), 'cliente', ['cliente_id'], ['id'])
        if not has_fk_material and batch_op.f('fk_solicitacao_material_formador_material_disponivel_id_material_disponivel') not in existing_fks:
            batch_op.create_foreign_key(batch_op.f('fk_solicitacao_material_formador_material_disponivel_id_material_disponivel'), 'material_disponivel', ['material_disponivel_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacao_material_formador', schema=None) as batch_op:
        existing_cols = {col['name'] for col in inspector.get_columns("solicitacao_material_formador")}
        existing_fks = {fk['name'] for fk in inspector.get_foreign_keys("solicitacao_material_formador")}
        batch_op.drop_constraint(batch_op.f('fk_solicitacao_material_formador_material_disponivel_id_material_disponivel'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_solicitacao_material_formador_cliente_id_cliente'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_solicitacao_material_formador_formador_id_ministrante'), type_='foreignkey')
        batch_op.create_foreign_key('fk_solicitacao_material_formador_material_disponivel_id_materia', 'material_disponivel', ['material_disponivel_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_solicitacao_material_formador_formador_id_ministrante', 'ministrante', ['formador_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_solicitacao_material_formador_cliente_id_cliente', 'cliente', ['cliente_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('ix_solicitacao_material_formador_status', ['status'], unique=False)
        batch_op.create_index('ix_solicitacao_material_formador_formador_id', ['formador_id'], unique=False)
        batch_op.create_index('ix_solicitacao_material_formador_data_solicitacao', ['data_solicitacao'], unique=False)
        batch_op.create_index('ix_solicitacao_material_formador_cliente_id', ['cliente_id'], unique=False)
        batch_op.alter_column('data_solicitacao',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('entregue',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pendente'::character varying"))
        batch_op.alter_column('justificativa',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('unidade_medida',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('nome_material',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               nullable=True)

    with op.batch_alter_table('material_disponivel', schema=None) as batch_op:
        existing_cols = {col['name'] for col in inspector.get_columns("material_disponivel")}
        existing_fks = {fk['name'] for fk in inspector.get_foreign_keys("material_disponivel")}
        batch_op.drop_constraint(batch_op.f('fk_material_disponivel_cliente_id_cliente'), type_='foreignkey')
        batch_op.create_foreign_key('fk_material_disponivel_cliente_id_cliente', 'cliente', ['cliente_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('ix_material_disponivel_cliente_id', ['cliente_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('ativo',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('disponivel_para_solicitacao',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
