"""empty message

Revision ID: 45cb50e9c9a6
Revises: 6579a97e890f
Create Date: 2025-09-02 20:10:42.259403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45cb50e9c9a6'
down_revision = '6579a97e890f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_atualizacao', sa.DateTime(), nullable=True))
        batch_op.alter_column('preco_unitario',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               nullable=True,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.alter_column('preco_unitario',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.drop_column('data_atualizacao')

    # ### end Alembic commands ###
