"""relatorio material ministrante atualizado com m tipo

Revision ID: 4a423c99fb29
Revises: 52ec98ef849d
Create Date: 2025-02-06 10:19:01.879872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a423c99fb29'
down_revision = '52ec98ef849d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
