"""add payment_id and created_at to inscricao

Revision ID: 4b08ba12e158
Revises: e088bd8f30ca
Create Date: 2025-04-10 22:14:19.093372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b08ba12e158'
down_revision = 'e088bd8f30ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscricao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_id', sa.String(length=64), nullable=True))
        # 👇 ajuste esta linha aqui para incluir um valor padrão inicial
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, 
                                      server_default=sa.func.now()))
        batch_op.create_index(batch_op.f('ix_inscricao_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inscricao_payment_id'), ['payment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscricao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inscricao_payment_id'))
        batch_op.drop_index(batch_op.f('ix_inscricao_created_at'))
        batch_op.drop_column('created_at')
        batch_op.drop_column('payment_id')

    # ### end Alembic commands ###
