"""initial migration

Revision ID: 526d79e887b5
Revises: 
Create Date: 2025-04-09 00:05:21.147933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '526d79e887b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracao_cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('habilitar_submissao_trabalhos', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracao_cliente', schema=None) as batch_op:
        batch_op.drop_column('habilitar_submissao_trabalhos')

    # ### end Alembic commands ###
