"""relatorio material ministrante atualizado

Revision ID: 52ec98ef849d
Revises: 791d1ab784a0
Create Date: 2025-02-06 10:07:45.958625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52ec98ef849d'
down_revision = '791d1ab784a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
