"""empty message

Revision ID: 5883528bda20
Revises: 059afbcdc79f
Create Date: 2025-06-20 14:25:06.653108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5883528bda20'
down_revision = '059afbcdc79f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracao_cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allowed_file_types', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracao_cliente', schema=None) as batch_op:
        batch_op.drop_column('allowed_file_types')

    # ### end Alembic commands ###
