"""Correção relação ministrante

Revision ID: 66d5ecbe41d2
Revises: 1fd10484cc3a
Create Date: 2025-02-06 18:57:20.349959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66d5ecbe41d2'
down_revision = '1fd10484cc3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
