"""empty message

Revision ID: 66f23e77b98d
Revises: 64d145b137c7
Create Date: 2025-06-16 15:45:50.165327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66f23e77b98d'
down_revision = '64d145b137c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracao_cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mostrar_taxa', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracao_cliente', schema=None) as batch_op:
        batch_op.drop_column('mostrar_taxa')

    # ### end Alembic commands ###
