"""Adicionando campo habilitar_feedback na tabela configuracao

Revision ID: 693eb570e44a
Revises: 
Create Date: 2025-02-03 19:57:48.484411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '693eb570e44a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('habilitar_feedback', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracao', schema=None) as batch_op:
        batch_op.drop_column('habilitar_feedback')

    # ### end Alembic commands ###
