"""Adicionando foto e categorias_formacao ao Ministrante

Revision ID: 6d9072416e97
Revises: 12403fba5a43
Create Date: 2025-03-12 22:50:52.838652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d9072416e97'
down_revision = '12403fba5a43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ministrante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categorias_formacao', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('foto', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ministrante', schema=None) as batch_op:
        batch_op.drop_column('foto')
        batch_op.drop_column('categorias_formacao')

    # ### end Alembic commands ###
