"""empty message

Revision ID: 716414415b8a
Revises: 5ffe4399fa5b
Create Date: 2025-09-18 10:57:56.034617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '716414415b8a'
down_revision = '5ffe4399fa5b'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        existing_cols = {col['name'] for col in inspector.get_columns("usuario")}
        existing_fks = {fk['name'] for fk in inspector.get_foreign_keys("usuario")}
        if "pode_aprovar_compras" not in existing_cols:
            batch_op.add_column(sa.Column('pode_aprovar_compras', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        existing_cols = {col['name'] for col in inspector.get_columns("usuario")}
        existing_fks = {fk['name'] for fk in inspector.get_foreign_keys("usuario")}
        batch_op.drop_column('pode_aprovar_compras')

    # ### end Alembic commands ###
