"""empty message

Revision ID: 716414415b8a
Revises: 5ffe4399fa5b
Create Date: 2025-09-18 10:57:56.034617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '716414415b8a'
down_revision = '5ffe4399fa5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pode_aprovar_compras', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('pode_aprovar_compras')

    # ### end Alembic commands ###
