"""empty message

Revision ID: 750863e7b1d2
Revises: 401f2480b537
Create Date: 2025-09-12 21:37:02.414381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '750863e7b1d2'
down_revision = '401f2480b537'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_disponivel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('tipo_material', sa.String(length=100), nullable=False),
    sa.Column('unidade_medida', sa.String(length=50), nullable=False),
    sa.Column('quantidade_minima_pedido', sa.Integer(), nullable=False),
    sa.Column('quantidade_maxima_pedido', sa.Integer(), nullable=False),
    sa.Column('disponivel_para_solicitacao', sa.Boolean(), nullable=True),
    sa.Column('quantidade_estoque', sa.Integer(), nullable=False),
    sa.Column('estoque_minimo', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('fk_material_disponivel_cliente_id_cliente')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_material_disponivel'))
    )
    op.create_table('solicitacao_material_formador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('formador_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('material_disponivel_id', sa.Integer(), nullable=True),
    sa.Column('tipo_solicitacao', sa.String(length=20), nullable=False),
    sa.Column('nome_material', sa.String(length=255), nullable=False),
    sa.Column('descricao_material', sa.Text(), nullable=True),
    sa.Column('unidade_medida', sa.String(length=50), nullable=False),
    sa.Column('quantidade_solicitada', sa.Integer(), nullable=False),
    sa.Column('justificativa', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('quantidade_aprovada', sa.Integer(), nullable=True),
    sa.Column('observacoes_cliente', sa.Text(), nullable=True),
    sa.Column('entregue', sa.Boolean(), nullable=True),
    sa.Column('data_entrega', sa.DateTime(), nullable=True),
    sa.Column('observacoes_entrega', sa.Text(), nullable=True),
    sa.Column('data_solicitacao', sa.DateTime(), nullable=True),
    sa.Column('data_resposta', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('fk_solicitacao_material_formador_cliente_id_cliente')),
    sa.ForeignKeyConstraint(['formador_id'], ['ministrante.id'], name=op.f('fk_solicitacao_material_formador_formador_id_ministrante')),
    sa.ForeignKeyConstraint(['material_disponivel_id'], ['material_disponivel.id'], name=op.f('fk_solicitacao_material_formador_material_disponivel_id_material_disponivel')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_solicitacao_material_formador'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitacao_material_formador')
    op.drop_table('material_disponivel')
    # ### end Alembic commands ###
