"""relatorio material ministrante

Revision ID: 791d1ab784a0
Revises: 9108c0457088
Create Date: 2025-02-06 09:13:16.032762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '791d1ab784a0'
down_revision = '9108c0457088'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oficina', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ministrante_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'ministrante', ['ministrante_id'], ['id'])
        batch_op.drop_column('ministrante')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oficina', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ministrante', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('ministrante_id')

    # ### end Alembic commands ###
