"""nova feature

Revision ID: 7d9bf72dc081
Revises: abc123456789
Create Date: 2025-07-01 12:06:42.126786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d9bf72dc081'
down_revision = 'abc123456789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('revisor_process', schema=None) as batch_op:
        batch_op.add_column(sa.Column('availability_start', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('availability_end', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('exibir_para_participantes', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('revisor_process', schema=None) as batch_op:
        batch_op.drop_column('exibir_para_participantes')
        batch_op.drop_column('availability_end')
        batch_op.drop_column('availability_start')

    # ### end Alembic commands ###
