"""Adicionar modelo Evento com campos de data

Revision ID: 7dfb3d9b2972
Revises: 
Create Date: 2025-03-16 01:01:42.992161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dfb3d9b2972'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_inicio', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('data_fim', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('hora_inicio', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('hora_fim', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.drop_column('hora_fim')
        batch_op.drop_column('hora_inicio')
        batch_op.drop_column('data_fim')
        batch_op.drop_column('data_inicio')

    # ### end Alembic commands ###
