"""add boleto_url to inscricao

Revision ID: 858b614d17da
Revises: 4b08ba12e158
Create Date: 2025-04-11 11:02:37.096241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '858b614d17da'
down_revision = '4b08ba12e158'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscricao', schema=None) as batch_op:
         batch_op.add_column(
            sa.Column('boleto_url',
                      sa.String(length=512),
                      nullable=True)     
                            )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscricao', schema=None) as batch_op:
        batch_op.drop_column('boleto_url')

    # ### end Alembic commands ###
