"""Add InscricaoEvento model

Revision ID: 89e1ecaf4910
Revises: 8f11731efdf6
Create Date: 2025-04-03 00:59:42.209640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89e1ecaf4910'
down_revision = '8f11731efdf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_inscricao_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'evento_inscricao_tipo', ['tipo_inscricao_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tipo_inscricao_id')

    # ### end Alembic commands ###
