"""editar, habilitar e restringir cliente

Revision ID: 8ba7a9a30ec0
Revises: 8c82bb28b0be
Create Date: 2025-02-23 16:50:24.266553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ba7a9a30ec0'
down_revision = '8c82bb28b0be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('oficina', 'cliente_id', nullable=True)
    with op.batch_alter_table('inscricao', schema=None) as batch_op:
        batch_op.drop_constraint('inscricao_cliente_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'cliente', ['cliente_id'], ['id'])

    with op.batch_alter_table('oficina', schema=None) as batch_op:
        batch_op.alter_column('cliente_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('oficina_cliente_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'cliente', ['cliente_id'], ['id'])

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint('usuario_cliente_id_fkey1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'cliente', ['cliente_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    op.alter_column('oficina', 'cliente_id', nullable=False)
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('usuario_cliente_id_fkey1', 'clientes', ['cliente_id'], ['id'])

    with op.batch_alter_table('oficina', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('oficina_cliente_id_fkey', 'clientes', ['cliente_id'], ['id'])
        batch_op.alter_column('cliente_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('inscricao', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('inscricao_cliente_id_fkey', 'clientes', ['cliente_id'], ['id'])

    op.create_table('clientes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='clientes_pkey')
    )
    # ### end Alembic commands ###
