"""Add habilitar_certificado_individual field

Revision ID: 8bbad833032d
Revises: 00a3ee58ef28
Create Date: 2025-02-21 17:15:58.752625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bbad833032d'
down_revision = '00a3ee58ef28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evento')
    op.drop_table('cliente')
    with op.batch_alter_table('configuracao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('habilitar_certificado_individual', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracao', schema=None) as batch_op:
        batch_op.drop_column('habilitar_certificado_individual')

    op.create_table('cliente',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('cliente_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('cnpj', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=150), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('senha', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='cliente_pkey'),
    sa.UniqueConstraint('cnpj', name='cliente_cnpj_key'),
    sa.UniqueConstraint('email', name='cliente_email_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('evento',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('data_inicio', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('data_fim', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('cliente_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name='evento_cliente_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='evento_pkey')
    )
    # ### end Alembic commands ###
