"""empty message

Revision ID: 8bfe3fda20ef
Revises: db72ea16fd82
Create Date: 2025-08-29 17:47:48.182595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bfe3fda20ef'
down_revision = 'db72ea16fd82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aluno_visitante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_necessidade_especial', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('descricao_necessidade_especial', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aluno_visitante', schema=None) as batch_op:
        batch_op.drop_column('descricao_necessidade_especial')
        batch_op.drop_column('tipo_necessidade_especial')

    # ### end Alembic commands ###
