"""Add InscricaoEvento model

Revision ID: 8f11731efdf6
Revises: f7abe80e3351
Create Date: 2025-04-02 18:40:22.865149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f11731efdf6'
down_revision = 'f7abe80e3351'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscricao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_inscricao_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('inscricao_tipo_inscricao_evento_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'inscricao_tipo', ['tipo_inscricao_id'], ['id'])
        batch_op.drop_column('tipo_inscricao_evento_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscricao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_inscricao_evento_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('inscricao_tipo_inscricao_evento_id_fkey', 'evento_inscricao_tipo', ['tipo_inscricao_evento_id'], ['id'])
        batch_op.drop_column('tipo_inscricao_id')

    # ### end Alembic commands ###
