"""ajusta created_at nullable

Revision ID: 8f17baaac6c4
Revises: 
Create Date: 2025-04-11 12:54:45.210421

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8f17baaac6c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscricao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column(
        'created_at',
        sa.DateTime(),
        nullable=False,
        server_default=sa.text('NOW()')  # ou CURRENT_TIMESTAMP
    ))
        batch_op.add_column(sa.Column('boleto_url', sa.String(length=512), nullable=True))
        batch_op.create_index(batch_op.f('ix_inscricao_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inscricao_payment_id'), ['payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inscricao_status_pagamento'), ['status_pagamento'], unique=False)

    with op.batch_alter_table('ministrante', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ministrante', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('inscricao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inscricao_status_pagamento'))
        batch_op.drop_index(batch_op.f('ix_inscricao_payment_id'))
        batch_op.drop_index(batch_op.f('ix_inscricao_created_at'))
        batch_op.drop_column('boleto_url')
        batch_op.drop_column('created_at')
        batch_op.drop_column('payment_id')

    # ### end Alembic commands ###
