"""Add InscricaoEvento model

Revision ID: 908e444a0425
Revises: 161829795685
Create Date: 2025-04-02 16:16:12.351725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '908e444a0425'
down_revision = '161829795685'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamento_visita', schema=None) as batch_op:
        batch_op.add_column(sa.Column('escola_codigo_inep', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('turma', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('data_cancelamento', sa.DateTime(), nullable=True))

    with op.batch_alter_table('inscricao', schema=None) as batch_op:
        batch_op.drop_constraint('inscricao_tipo_inscricao_evento_id_fkey', type_='foreignkey')
        batch_op.drop_column('tipo_inscricao_evento_id')

    with op.batch_alter_table('sala_visitacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sala_visitacao', schema=None) as batch_op:
        batch_op.drop_column('nome')

    with op.batch_alter_table('inscricao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_inscricao_evento_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('inscricao_tipo_inscricao_evento_id_fkey', 'evento_inscricao_tipo', ['tipo_inscricao_evento_id'], ['id'])

    with op.batch_alter_table('agendamento_visita', schema=None) as batch_op:
        batch_op.drop_column('data_cancelamento')
        batch_op.drop_column('turma')
        batch_op.drop_column('escola_codigo_inep')

    # ### end Alembic commands ###
