"""Initial migration

Revision ID: 9108c0457088
Revises: 693eb570e44a
Create Date: 2025-02-05 21:54:35.323842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9108c0457088'
down_revision = '693eb570e44a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oficina_dia')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oficina_dia',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('oficina_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('horario_inicio', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('horario_fim', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('palavra_chave_manha', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('palavra_chave_tarde', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['oficina_id'], ['oficina.id'], name='oficina_dia_oficina_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='oficina_dia_pkey')
    )
    # ### end Alembic commands ###
