"""initial migration

Revision ID: 9a2b6411ecbe
Revises: 
Create Date: 2025-04-13 16:21:08.139747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a2b6411ecbe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('preco_lote_inscricao')
    with op.batch_alter_table('inscricao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lote_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'lote_inscricao', ['lote_id'], ['id'])

    with op.batch_alter_table('lote_inscricao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qtd_maxima', sa.Integer(), nullable=True))
        batch_op.alter_column('ordem',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('numero_maximo')
        batch_op.drop_column('tipo_limite')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lote_inscricao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_limite', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('numero_maximo', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.alter_column('ordem',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('qtd_maxima')

    with op.batch_alter_table('inscricao', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('lote_id')

    op.create_table('preco_lote_inscricao',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lote_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo_inscricao_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('preco', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['lote_id'], ['lote_inscricao.id'], name='preco_lote_inscricao_lote_id_fkey'),
    sa.ForeignKeyConstraint(['tipo_inscricao_id'], ['evento_inscricao_tipo.id'], name='preco_lote_inscricao_tipo_inscricao_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='preco_lote_inscricao_pkey')
    )
    # ### end Alembic commands ###
