"""add indexes to checkin

Revision ID: a5154a3f3a4c
Revises: 8d8534bb7a94
Create Date: 2025-07-16 20:26:24.826155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5154a3f3a4c'
down_revision = '8d8534bb7a94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_checkin_usuario_id'), 'checkin', ['usuario_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_checkin_oficina_id'), 'checkin', ['oficina_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_checkin_evento_id'), 'checkin', ['evento_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_checkin_data_hora'), 'checkin', ['data_hora'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_checkin_cliente_id'), 'checkin', ['cliente_id'], unique=False, if_not_exists=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_checkin_cliente_id'), table_name='checkin', if_exists=True)
    op.drop_index(op.f('ix_checkin_data_hora'), table_name='checkin', if_exists=True)
    op.drop_index(op.f('ix_checkin_evento_id'), table_name='checkin', if_exists=True)
    op.drop_index(op.f('ix_checkin_oficina_id'), table_name='checkin', if_exists=True)
    op.drop_index(op.f('ix_checkin_usuario_id'), table_name='checkin', if_exists=True)
    # ### end Alembic commands ###
