"""inicializando

Revision ID: aad428c4ac42
Revises: 
Create Date: 2025-03-25 14:33:56.816495

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aad428c4ac42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posicao_elemento_certificado')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posicao_elemento_certificado',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo_elemento', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('pos_x', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('pos_y', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('atualizado_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name='posicao_elemento_certificado_cliente_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='posicao_elemento_certificado_pkey')
    )
    # ### end Alembic commands ###
