"""Add formador_polo table

Revision ID: add_formador_polo_table
Revises: 
Create Date: 2025-01-14 11:45:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_formador_polo_table'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formador_polo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('formador_id', sa.Integer(), nullable=False),
    sa.Column('polo_id', sa.Integer(), nullable=False),
    sa.Column('data_atribuicao', sa.DateTime(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['formador_id'], ['ministrante.id'], ),
    sa.ForeignKeyConstraint(['polo_id'], ['polo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('formador_polo')
    # ### end Alembic commands ###