"""Add etapa column to campos_formulario table

Revision ID: add_etapa_campo
Revises: 
Create Date: 2024-01-10 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_etapa_campo'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campos_formulario', sa.Column('etapa', sa.Integer(), nullable=True, default=1))
    
    # Set default value for existing records
    op.execute("UPDATE campos_formulario SET etapa = 1 WHERE etapa IS NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campos_formulario', 'etapa')
    # ### end Alembic commands ###