"""Add certificado revisor tables

Revision ID: cert_revisor_001
Revises: d4889a23ebd8
Create Date: 2025-01-15 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cert_revisor_001'
down_revision = 'd4889a23ebd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create certificado_revisor_config table
    op.create_table('certificado_revisor_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=True),
    sa.Column('titulo_certificado', sa.String(length=200), nullable=False),
    sa.Column('texto_certificado', sa.Text(), nullable=False),
    sa.Column('fundo_certificado', sa.String(length=500), nullable=True),
    sa.Column('liberacao_automatica', sa.Boolean(), nullable=True),
    sa.Column('criterio_trabalhos_minimos', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Create certificado_revisor table
    op.create_table('certificado_revisor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('revisor_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=True),
    sa.Column('liberado', sa.Boolean(), nullable=True),
    sa.Column('data_liberacao', sa.DateTime(), nullable=True),
    sa.Column('liberado_por', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('texto_personalizado', sa.Text(), nullable=True),
    sa.Column('fundo_personalizado', sa.String(length=500), nullable=True),
    sa.Column('trabalhos_revisados', sa.Integer(), nullable=True),
    sa.Column('data_inicio_atividade', sa.DateTime(), nullable=True),
    sa.Column('data_fim_atividade', sa.DateTime(), nullable=True),
    sa.Column('arquivo_path', sa.String(length=500), nullable=True),
    sa.Column('hash_verificacao', sa.String(length=64), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id'], ),
    sa.ForeignKeyConstraint(['liberado_por'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['revisor_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Create indexes for better performance
    op.create_index('ix_certificado_revisor_config_cliente_evento', 'certificado_revisor_config', ['cliente_id', 'evento_id'], unique=False)
    op.create_index('ix_certificado_revisor_revisor_cliente', 'certificado_revisor', ['revisor_id', 'cliente_id'], unique=False)
    op.create_index('ix_certificado_revisor_liberado', 'certificado_revisor', ['liberado'], unique=False)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop indexes
    op.drop_index('ix_certificado_revisor_liberado', table_name='certificado_revisor')
    op.drop_index('ix_certificado_revisor_revisor_cliente', table_name='certificado_revisor')
    op.drop_index('ix_certificado_revisor_config_cliente_evento', table_name='certificado_revisor_config')
    
    # Drop tables
    op.drop_table('certificado_revisor')
    op.drop_table('certificado_revisor_config')
    
    # ### end Alembic commands ###

