"""Add status_avaliacao to RespostaFormulario

Revision ID: af2f8513fa83
Revises: caf1b7504a7c
Create Date: 2025-03-05 13:22:18.129606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af2f8513fa83'
down_revision = 'caf1b7504a7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('respostas_formulario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_avaliacao', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('respostas_formulario', schema=None) as batch_op:
        batch_op.drop_column('status_avaliacao')

    # ### end Alembic commands ###
