"""empty message

Revision ID: b028d7157f10
Revises: f2205e8d2be8
Create Date: 2025-09-09 08:52:12.000025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b028d7157f10'
down_revision = 'f2205e8d2be8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campos_formulario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('etapa', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campos_formulario', schema=None) as batch_op:
        batch_op.drop_column('etapa')

    # ### end Alembic commands ###
