"""empty message

Revision ID: b367611ada28
Revises: a296c1a703a2
Create Date: 2025-09-25 12:04:18.745896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b367611ada28'
down_revision = 'a296c1a703a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cache_relatorio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chave_cache', sa.String(length=255), nullable=False),
    sa.Column('dados_cache', sa.Text(), nullable=False),
    sa.Column('tipo_dados', sa.String(length=50), nullable=False),
    sa.Column('filtros_hash', sa.String(length=64), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_expiracao', sa.DateTime(), nullable=False),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cache_relatorio')),
    sa.UniqueConstraint('chave_cache', name=op.f('uq_cache_relatorio_chave_cache'))
    )
    op.create_table('metrica_bi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('tipo_metrica', sa.String(length=30), nullable=False),
    sa.Column('formula', sa.Text(), nullable=True),
    sa.Column('cor', sa.String(length=7), nullable=True),
    sa.Column('icone', sa.String(length=50), nullable=True),
    sa.Column('unidade', sa.String(length=20), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metrica_bi'))
    )
    op.create_table('alertas_bi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('tipo_alerta', sa.String(length=50), nullable=False),
    sa.Column('metrica_id', sa.Integer(), nullable=False),
    sa.Column('condicao', sa.String(length=20), nullable=False),
    sa.Column('valor_limite', sa.Float(), nullable=False),
    sa.Column('periodo_verificacao', sa.Integer(), nullable=True),
    sa.Column('usuarios_notificar', sa.Text(), nullable=True),
    sa.Column('canais_notificacao', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('ultima_verificacao', sa.DateTime(), nullable=True),
    sa.Column('ultimo_disparo', sa.DateTime(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['metrica_id'], ['metrica_bi.id'], name=op.f('fk_alertas_bi_metrica_id_metrica_bi')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alertas_bi'))
    )
    op.create_table('lembrete_oficina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('tipo', sa.Enum('MANUAL', 'AUTOMATICO', name='tipolembrete'), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'ENVIADO', 'FALHOU', 'CANCELADO', name='statuslembrete'), nullable=False),
    sa.Column('dias_antecedencia', sa.Integer(), nullable=True),
    sa.Column('data_envio_agendada', sa.DateTime(), nullable=True),
    sa.Column('enviar_todas_oficinas', sa.Boolean(), nullable=True),
    sa.Column('oficina_ids', sa.Text(), nullable=True),
    sa.Column('usuario_ids', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_envio', sa.DateTime(), nullable=True),
    sa.Column('total_destinatarios', sa.Integer(), nullable=True),
    sa.Column('total_enviados', sa.Integer(), nullable=True),
    sa.Column('total_falhas', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('fk_lembrete_oficina_cliente_id_cliente')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lembrete_oficina'))
    )
    op.create_table('widget_bi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('tipo_widget', sa.String(length=50), nullable=False),
    sa.Column('configuracao', sa.Text(), nullable=True),
    sa.Column('query_sql', sa.Text(), nullable=True),
    sa.Column('metrica_id', sa.Integer(), nullable=True),
    sa.Column('largura', sa.Integer(), nullable=True),
    sa.Column('altura', sa.Integer(), nullable=True),
    sa.Column('posicao_x', sa.Integer(), nullable=True),
    sa.Column('posicao_y', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['metrica_id'], ['metrica_bi.id'], name=op.f('fk_widget_bi_metrica_id_metrica_bi')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_widget_bi'))
    )
    op.create_table('atividade_multipla_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('carga_horaria_total', sa.String(length=10), nullable=False),
    sa.Column('tipo_atividade', sa.String(length=50), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=True),
    sa.Column('permitir_checkin_multiplas_datas', sa.Boolean(), nullable=True),
    sa.Column('gerar_lista_frequencia', sa.Boolean(), nullable=True),
    sa.Column('exigir_presenca_todas_datas', sa.Boolean(), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('fk_atividade_multipla_data_cliente_id_cliente')),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id'], name=op.f('fk_atividade_multipla_data_evento_id_evento')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_atividade_multipla_data'))
    )
    op.create_table('atividade_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atividade_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('horario_inicio', sa.Time(), nullable=False),
    sa.Column('horario_fim', sa.Time(), nullable=False),
    sa.Column('palavra_chave_manha', sa.String(length=50), nullable=True),
    sa.Column('palavra_chave_tarde', sa.String(length=50), nullable=True),
    sa.Column('carga_horaria_data', sa.String(length=10), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['atividade_id'], ['atividade_multipla_data.id'], name=op.f('fk_atividade_data_atividade_id_atividade_multipla_data')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_atividade_data'))
    )
    op.create_table('atividade_ministrantes_association',
    sa.Column('atividade_id', sa.Integer(), nullable=False),
    sa.Column('ministrante_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['atividade_id'], ['atividade_multipla_data.id'], name=op.f('fk_atividade_ministrantes_association_atividade_id_atividade_multipla_data')),
    sa.ForeignKeyConstraint(['ministrante_id'], ['ministrante.id'], name=op.f('fk_atividade_ministrantes_association_ministrante_id_ministrante')),
    sa.PrimaryKeyConstraint('atividade_id', 'ministrante_id', name=op.f('pk_atividade_ministrantes_association'))
    )
    op.create_table('perguntas_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('oficina_id', sa.Integer(), nullable=True),
    sa.Column('atividade_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('tipo', sa.Enum('TEXTO_LIVRE', 'MULTIPLA_ESCOLHA', 'ESCALA_NUMERICA', 'SIM_NAO', name='tipopergunta'), nullable=False),
    sa.Column('opcoes', sa.Text(), nullable=True),
    sa.Column('obrigatoria', sa.Boolean(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('fk_perguntas_feedback_cliente_id_cliente')),
    sa.ForeignKeyConstraint(['oficina_id'], ['oficina.id'], name=op.f('fk_perguntas_feedback_oficina_id_oficina')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_perguntas_feedback'))
    )
    op.create_table('checkin_atividade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atividade_id', sa.Integer(), nullable=False),
    sa.Column('data_atividade_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.Column('palavra_chave', sa.String(length=50), nullable=False),
    sa.Column('turno', sa.String(length=10), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['atividade_id'], ['atividade_multipla_data.id'], name=op.f('fk_checkin_atividade_atividade_id_atividade_multipla_data')),
    sa.ForeignKeyConstraint(['data_atividade_id'], ['atividade_data.id'], name=op.f('fk_checkin_atividade_data_atividade_id_atividade_data')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_checkin_atividade_usuario_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checkin_atividade'))
    )
    op.create_table('dashboard_bi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('usuario_criador_id', sa.Integer(), nullable=False),
    sa.Column('layout_config', sa.Text(), nullable=True),
    sa.Column('widgets_config', sa.Text(), nullable=True),
    sa.Column('filtros_padrao', sa.Text(), nullable=True),
    sa.Column('publico', sa.Boolean(), nullable=True),
    sa.Column('usuarios_permitidos', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('fk_dashboard_bi_cliente_id_cliente')),
    sa.ForeignKeyConstraint(['usuario_criador_id'], ['usuario.id'], name=op.f('fk_dashboard_bi_usuario_criador_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dashboard_bi'))
    )
    op.create_table('feedback_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('oficina_id', sa.Integer(), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=True),
    sa.Column('respondida', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['oficina_id'], ['oficina.id'], name=op.f('fk_feedback_sessions_oficina_id_oficina')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_feedback_sessions_usuario_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedback_sessions')),
    sa.UniqueConstraint('token', name=op.f('uq_feedback_sessions_token'))
    )
    op.create_table('frequencia_atividade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atividade_id', sa.Integer(), nullable=False),
    sa.Column('data_atividade_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('presente_manha', sa.Boolean(), nullable=True),
    sa.Column('presente_tarde', sa.Boolean(), nullable=True),
    sa.Column('presente_dia_inteiro', sa.Boolean(), nullable=True),
    sa.Column('data_checkin_manha', sa.DateTime(), nullable=True),
    sa.Column('data_checkin_tarde', sa.DateTime(), nullable=True),
    sa.Column('palavra_chave_usada_manha', sa.String(length=50), nullable=True),
    sa.Column('palavra_chave_usada_tarde', sa.String(length=50), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['atividade_id'], ['atividade_multipla_data.id'], name=op.f('fk_frequencia_atividade_atividade_id_atividade_multipla_data')),
    sa.ForeignKeyConstraint(['data_atividade_id'], ['atividade_data.id'], name=op.f('fk_frequencia_atividade_data_atividade_id_atividade_data')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_frequencia_atividade_usuario_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_frequencia_atividade'))
    )
    op.create_table('lembrete_envio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lembrete_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('oficina_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'ENVIADO', 'FALHOU', 'CANCELADO', name='statuslembrete'), nullable=False),
    sa.Column('data_envio', sa.DateTime(), nullable=True),
    sa.Column('erro_mensagem', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lembrete_id'], ['lembrete_oficina.id'], name=op.f('fk_lembrete_envio_lembrete_id_lembrete_oficina')),
    sa.ForeignKeyConstraint(['oficina_id'], ['oficina.id'], name=op.f('fk_lembrete_envio_oficina_id_oficina')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_lembrete_envio_usuario_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lembrete_envio'))
    )
    op.create_table('relatorio_bi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('tipo_relatorio', sa.String(length=50), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('usuario_criador_id', sa.Integer(), nullable=False),
    sa.Column('filtros_aplicados', sa.Text(), nullable=True),
    sa.Column('periodo_inicio', sa.Date(), nullable=True),
    sa.Column('periodo_fim', sa.Date(), nullable=True),
    sa.Column('dados_relatorio', sa.Text(), nullable=True),
    sa.Column('metricas_calculadas', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.Column('ultima_execucao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('fk_relatorio_bi_cliente_id_cliente')),
    sa.ForeignKeyConstraint(['usuario_criador_id'], ['usuario.id'], name=op.f('fk_relatorio_bi_usuario_criador_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_relatorio_bi'))
    )
    op.create_table('respostas_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pergunta_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('oficina_id', sa.Integer(), nullable=False),
    sa.Column('resposta_texto', sa.Text(), nullable=True),
    sa.Column('resposta_numerica', sa.Integer(), nullable=True),
    sa.Column('resposta_escolha', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['oficina_id'], ['oficina.id'], name=op.f('fk_respostas_feedback_oficina_id_oficina')),
    sa.ForeignKeyConstraint(['pergunta_id'], ['perguntas_feedback.id'], name=op.f('fk_respostas_feedback_pergunta_id_perguntas_feedback')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_respostas_feedback_usuario_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_respostas_feedback'))
    )
    op.create_table('exportacao_relatorio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relatorio_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('formato', sa.String(length=10), nullable=False),
    sa.Column('filtros_aplicados', sa.Text(), nullable=True),
    sa.Column('configuracao_export', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('arquivo_path', sa.String(length=500), nullable=True),
    sa.Column('tamanho_arquivo', sa.Integer(), nullable=True),
    sa.Column('mensagem_erro', sa.Text(), nullable=True),
    sa.Column('data_inicio', sa.DateTime(), nullable=True),
    sa.Column('data_conclusao', sa.DateTime(), nullable=True),
    sa.Column('tempo_processamento', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['relatorio_id'], ['relatorio_bi.id'], name=op.f('fk_exportacao_relatorio_relatorio_id_relatorio_bi')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_exportacao_relatorio_usuario_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exportacao_relatorio'))
    )
    with op.batch_alter_table('checkin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('atividade_multipla_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('data_atividade_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('turno', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('ip_address', sa.String(length=45), nullable=True))
        batch_op.add_column(sa.Column('user_agent', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_checkin_atividade_multipla_id'), ['atividade_multipla_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_checkin_data_atividade_id'), ['data_atividade_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_checkin_atividade_multipla_id_atividade_multipla_data'), 'atividade_multipla_data', ['atividade_multipla_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_checkin_data_atividade_id_atividade_data'), 'atividade_data', ['data_atividade_id'], ['id'])

    with op.batch_alter_table('oficina', schema=None) as batch_op:
        batch_op.add_column(sa.Column('formador_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_oficina_formador_id_ministrante'), 'ministrante', ['formador_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oficina', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_oficina_formador_id_ministrante'), type_='foreignkey')
        batch_op.drop_column('formador_id')

    with op.batch_alter_table('checkin', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_checkin_data_atividade_id_atividade_data'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_checkin_atividade_multipla_id_atividade_multipla_data'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_checkin_data_atividade_id'))
        batch_op.drop_index(batch_op.f('ix_checkin_atividade_multipla_id'))
        batch_op.drop_column('user_agent')
        batch_op.drop_column('ip_address')
        batch_op.drop_column('turno')
        batch_op.drop_column('data_atividade_id')
        batch_op.drop_column('atividade_multipla_id')

    op.drop_table('exportacao_relatorio')
    op.drop_table('respostas_feedback')
    op.drop_table('relatorio_bi')
    op.drop_table('lembrete_envio')
    op.drop_table('frequencia_atividade')
    op.drop_table('feedback_sessions')
    op.drop_table('dashboard_bi')
    op.drop_table('checkin_atividade')
    op.drop_table('perguntas_feedback')
    op.drop_table('atividade_ministrantes_association')
    op.drop_table('atividade_data')
    op.drop_table('atividade_multipla_data')
    op.drop_table('widget_bi')
    op.drop_table('lembrete_oficina')
    op.drop_table('alertas_bi')
    op.drop_table('metrica_bi')
    op.drop_table('cache_relatorio')
    # ### end Alembic commands ###
