"""empty message

Revision ID: b530b6bab8f8
Revises: d1b3a515bc9e
Create Date: 2025-08-25 14:42:41.790992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b530b6bab8f8'
down_revision = 'd1b3a515bc9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamento_visita', schema=None) as batch_op:
        batch_op.drop_column('precisa_transporte')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamento_visita', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precisa_transporte', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
