"""Add atividade multipla data tables

Revision ID: b9f8e7d6c5a4
Revises: 
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b9f8e7d6c5a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create atividade_multipla_data table
    op.create_table('atividade_multipla_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('carga_horaria_total', sa.String(length=10), nullable=False),
    sa.Column('tipo_atividade', sa.String(length=50), nullable=False),
    sa.Column('permitir_checkin_multiplas_datas', sa.Boolean(), nullable=True),
    sa.Column('gerar_lista_frequencia', sa.Boolean(), nullable=True),
    sa.Column('exigir_presenca_todas_datas', sa.Boolean(), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Create atividade_data table
    op.create_table('atividade_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atividade_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('horario_inicio', sa.Time(), nullable=False),
    sa.Column('horario_fim', sa.Time(), nullable=False),
    sa.Column('palavra_chave_manha', sa.String(length=50), nullable=True),
    sa.Column('palavra_chave_tarde', sa.String(length=50), nullable=True),
    sa.Column('carga_horaria_data', sa.String(length=10), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['atividade_id'], ['atividade_multipla_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Create frequencia_atividade table
    op.create_table('frequencia_atividade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atividade_id', sa.Integer(), nullable=False),
    sa.Column('data_atividade_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('presente_manha', sa.Boolean(), nullable=True),
    sa.Column('presente_tarde', sa.Boolean(), nullable=True),
    sa.Column('presente_dia_inteiro', sa.Boolean(), nullable=True),
    sa.Column('data_checkin_manha', sa.DateTime(), nullable=True),
    sa.Column('data_checkin_tarde', sa.DateTime(), nullable=True),
    sa.Column('palavra_chave_usada_manha', sa.String(length=50), nullable=True),
    sa.Column('palavra_chave_usada_tarde', sa.String(length=50), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['atividade_id'], ['atividade_multipla_data.id'], ),
    sa.ForeignKeyConstraint(['data_atividade_id'], ['atividade_data.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Create checkin_atividade table
    op.create_table('checkin_atividade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atividade_id', sa.Integer(), nullable=False),
    sa.Column('data_atividade_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.Column('palavra_chave', sa.String(length=50), nullable=False),
    sa.Column('turno', sa.String(length=10), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['atividade_id'], ['atividade_multipla_data.id'], ),
    sa.ForeignKeyConstraint(['data_atividade_id'], ['atividade_data.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Create atividade_ministrantes_association table
    op.create_table('atividade_ministrantes_association',
    sa.Column('atividade_id', sa.Integer(), nullable=False),
    sa.Column('ministrante_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['atividade_id'], ['atividade_multipla_data.id'], ),
    sa.ForeignKeyConstraint(['ministrante_id'], ['ministrante.id'], ),
    sa.PrimaryKeyConstraint('atividade_id', 'ministrante_id')
    )
    
    # Add new columns to checkin table
    op.add_column('checkin', sa.Column('atividade_multipla_id', sa.Integer(), nullable=True))
    op.add_column('checkin', sa.Column('data_atividade_id', sa.Integer(), nullable=True))
    op.add_column('checkin', sa.Column('turno', sa.String(length=10), nullable=True))
    op.add_column('checkin', sa.Column('ip_address', sa.String(length=45), nullable=True))
    op.add_column('checkin', sa.Column('user_agent', sa.Text(), nullable=True))
    
    # Add foreign key constraints to checkin table
    op.create_foreign_key('fk_checkin_atividade_multipla', 'checkin', 'atividade_multipla_data', ['atividade_multipla_id'], ['id'])
    op.create_foreign_key('fk_checkin_data_atividade', 'checkin', 'atividade_data', ['data_atividade_id'], ['id'])
    
    # Create indexes for better performance
    op.create_index('ix_checkin_atividade_multipla_id', 'checkin', ['atividade_multipla_id'])
    op.create_index('ix_checkin_data_atividade_id', 'checkin', ['data_atividade_id'])
    op.create_index('ix_frequencia_atividade_usuario', 'frequencia_atividade', ['usuario_id'])
    op.create_index('ix_frequencia_atividade_atividade', 'frequencia_atividade', ['atividade_id'])
    op.create_index('ix_checkin_atividade_usuario', 'checkin_atividade', ['usuario_id'])
    op.create_index('ix_checkin_atividade_atividade', 'checkin_atividade', ['atividade_id'])
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop indexes
    op.drop_index('ix_checkin_atividade_atividade', table_name='checkin_atividade')
    op.drop_index('ix_checkin_atividade_usuario', table_name='checkin_atividade')
    op.drop_index('ix_frequencia_atividade_atividade', table_name='frequencia_atividade')
    op.drop_index('ix_frequencia_atividade_usuario', table_name='frequencia_atividade')
    op.drop_index('ix_checkin_data_atividade_id', table_name='checkin')
    op.drop_index('ix_checkin_atividade_multipla_id', table_name='checkin')
    
    # Drop foreign key constraints from checkin table
    op.drop_constraint('fk_checkin_data_atividade', 'checkin', type_='foreignkey')
    op.drop_constraint('fk_checkin_atividade_multipla', 'checkin', type_='foreignkey')
    
    # Drop new columns from checkin table
    op.drop_column('checkin', 'user_agent')
    op.drop_column('checkin', 'ip_address')
    op.drop_column('checkin', 'turno')
    op.drop_column('checkin', 'data_atividade_id')
    op.drop_column('checkin', 'atividade_multipla_id')
    
    # Drop tables
    op.drop_table('atividade_ministrantes_association')
    op.drop_table('checkin_atividade')
    op.drop_table('frequencia_atividade')
    op.drop_table('atividade_data')
    op.drop_table('atividade_multipla_data')
    
    # ### end Alembic commands ###
