"""empty message

Revision ID: bcc47937c57a
Revises: 4e433a7fffc8
Create Date: 2025-09-26 07:52:29.085905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcc47937c57a'
down_revision = '4e433a7fffc8'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cache_relatorio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chave_cache', sa.String(length=255), nullable=False),
    sa.Column('dados_cache', sa.Text(), nullable=False),
    sa.Column('tipo_dados', sa.String(length=50), nullable=False),
    sa.Column('filtros_hash', sa.String(length=64), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_expiracao', sa.DateTime(), nullable=False),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cache_relatorio')),
    sa.UniqueConstraint('chave_cache', name=op.f('uq_cache_relatorio_chave_cache'))
    )
    op.create_table('metrica_bi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('tipo_metrica', sa.String(length=30), nullable=False),
    sa.Column('formula', sa.Text(), nullable=True),
    sa.Column('cor', sa.String(length=7), nullable=True),
    sa.Column('icone', sa.String(length=50), nullable=True),
    sa.Column('unidade', sa.String(length=20), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metrica_bi'))
    )
    op.create_table('alertas_bi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('tipo_alerta', sa.String(length=50), nullable=False),
    sa.Column('metrica_id', sa.Integer(), nullable=False),
    sa.Column('condicao', sa.String(length=20), nullable=False),
    sa.Column('valor_limite', sa.Float(), nullable=False),
    sa.Column('periodo_verificacao', sa.Integer(), nullable=True),
    sa.Column('usuarios_notificar', sa.Text(), nullable=True),
    sa.Column('canais_notificacao', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('ultima_verificacao', sa.DateTime(), nullable=True),
    sa.Column('ultimo_disparo', sa.DateTime(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['metrica_id'], ['metrica_bi.id'], name=op.f('fk_alertas_bi_metrica_id_metrica_bi')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alertas_bi'))
    )
    op.create_table('lembrete_oficina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('tipo', sa.Enum('MANUAL', 'AUTOMATICO', name='tipolembrete'), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'ENVIADO', 'FALHOU', 'CANCELADO', name='statuslembrete'), nullable=False),
    sa.Column('dias_antecedencia', sa.Integer(), nullable=True),
    sa.Column('data_envio_agendada', sa.DateTime(), nullable=True),
    sa.Column('enviar_todas_oficinas', sa.Boolean(), nullable=True),
    sa.Column('oficina_ids', sa.Text(), nullable=True),
    sa.Column('usuario_ids', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_envio', sa.DateTime(), nullable=True),
    sa.Column('total_destinatarios', sa.Integer(), nullable=True),
    sa.Column('total_enviados', sa.Integer(), nullable=True),
    sa.Column('total_falhas', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('fk_lembrete_oficina_cliente_id_cliente')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lembrete_oficina'))
    )
    op.create_table('widget_bi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('tipo_widget', sa.String(length=50), nullable=False),
    sa.Column('configuracao', sa.Text(), nullable=True),
    sa.Column('query_sql', sa.Text(), nullable=True),
    sa.Column('metrica_id', sa.Integer(), nullable=True),
    sa.Column('largura', sa.Integer(), nullable=True),
    sa.Column('altura', sa.Integer(), nullable=True),
    sa.Column('posicao_x', sa.Integer(), nullable=True),
    sa.Column('posicao_y', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['metrica_id'], ['metrica_bi.id'], name=op.f('fk_widget_bi_metrica_id_metrica_bi')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_widget_bi'))
    )
    op.create_table('dashboard_bi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('usuario_criador_id', sa.Integer(), nullable=False),
    sa.Column('layout_config', sa.Text(), nullable=True),
    sa.Column('widgets_config', sa.Text(), nullable=True),
    sa.Column('filtros_padrao', sa.Text(), nullable=True),
    sa.Column('publico', sa.Boolean(), nullable=True),
    sa.Column('usuarios_permitidos', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('fk_dashboard_bi_cliente_id_cliente')),
    sa.ForeignKeyConstraint(['usuario_criador_id'], ['usuario.id'], name=op.f('fk_dashboard_bi_usuario_criador_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dashboard_bi'))
    )
    op.create_table('lembrete_envio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lembrete_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('oficina_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'ENVIADO', 'FALHOU', 'CANCELADO', name='statuslembrete'), nullable=False),
    sa.Column('data_envio', sa.DateTime(), nullable=True),
    sa.Column('erro_mensagem', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lembrete_id'], ['lembrete_oficina.id'], name=op.f('fk_lembrete_envio_lembrete_id_lembrete_oficina')),
    sa.ForeignKeyConstraint(['oficina_id'], ['oficina.id'], name=op.f('fk_lembrete_envio_oficina_id_oficina')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_lembrete_envio_usuario_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lembrete_envio'))
    )
    op.create_table('relatorio_bi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('tipo_relatorio', sa.String(length=50), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('usuario_criador_id', sa.Integer(), nullable=False),
    sa.Column('filtros_aplicados', sa.Text(), nullable=True),
    sa.Column('periodo_inicio', sa.Date(), nullable=True),
    sa.Column('periodo_fim', sa.Date(), nullable=True),
    sa.Column('dados_relatorio', sa.Text(), nullable=True),
    sa.Column('metricas_calculadas', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.Column('ultima_execucao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('fk_relatorio_bi_cliente_id_cliente')),
    sa.ForeignKeyConstraint(['usuario_criador_id'], ['usuario.id'], name=op.f('fk_relatorio_bi_usuario_criador_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_relatorio_bi'))
    )
    op.create_table('exportacao_relatorio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relatorio_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('formato', sa.String(length=10), nullable=False),
    sa.Column('filtros_aplicados', sa.Text(), nullable=True),
    sa.Column('configuracao_export', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('arquivo_path', sa.String(length=500), nullable=True),
    sa.Column('tamanho_arquivo', sa.Integer(), nullable=True),
    sa.Column('mensagem_erro', sa.Text(), nullable=True),
    sa.Column('data_inicio', sa.DateTime(), nullable=True),
    sa.Column('data_conclusao', sa.DateTime(), nullable=True),
    sa.Column('tempo_processamento', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['relatorio_id'], ['relatorio_bi.id'], name=op.f('fk_exportacao_relatorio_relatorio_id_relatorio_bi')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_exportacao_relatorio_usuario_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exportacao_relatorio'))
    )
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        existing_cols = {col['name'] for col in inspector.get_columns("assignment")}
        existing_fks = {fk['name'] for fk in inspector.get_foreign_keys("assignment")}
        if "is_reevaluation" not in existing_cols:
            batch_op.add_column(sa.Column('is_reevaluation', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        existing_cols = {col['name'] for col in inspector.get_columns("assignment")}
        existing_fks = {fk['name'] for fk in inspector.get_foreign_keys("assignment")}
        batch_op.drop_column('is_reevaluation')

    op.drop_table('exportacao_relatorio')
    op.drop_table('relatorio_bi')
    op.drop_table('lembrete_envio')
    op.drop_table('dashboard_bi')
    op.drop_table('widget_bi')
    op.drop_table('lembrete_oficina')
    op.drop_table('alertas_bi')
    op.drop_table('metrica_bi')
    op.drop_table('cache_relatorio')
    # ### end Alembic commands ###
