"""Adiciona qr_code_token em Inscricao

Revision ID: be263dd2462b
Revises: 6a233677f56d
Create Date: 2025-02-18 17:13:22.744260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be263dd2462b'
down_revision = '6a233677f56d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscricao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_code_token', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint(None, ['qr_code_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscricao', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('qr_code_token')

    # ### end Alembic commands ###
