"""Adicionando corretamente cliente_id na tabela Usuario

Revision ID: c3875974b814
Revises: 96e2a23a38a3
Create Date: 2025-02-22 21:10:19.813374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3875974b814'
down_revision = '96e2a23a38a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oficina', schema=None) as batch_op:
        batch_op.drop_constraint('oficina_cliente_id_fkey', type_='foreignkey')
        batch_op.drop_column('cliente_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oficina', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cliente_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('oficina_cliente_id_fkey', 'cliente', ['cliente_id'], ['id'])

    # ### end Alembic commands ###
