"""Add fields for certificate customization

Revision ID: c569ba14680d
Revises: 01a981839e0c
Create Date: 2025-02-28 23:43:55.326111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c569ba14680d'
down_revision = '01a981839e0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_certificado', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('fundo_certificado', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('assinatura_certificado', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_column('assinatura_certificado')
        batch_op.drop_column('fundo_certificado')
        batch_op.drop_column('logo_certificado')

    # ### end Alembic commands ###
