"""Add formador system models and relatorio configuravel models

Revision ID: c7b47ee06203
Revises: 11cf8bf6ec78
Create Date: 2025-09-12 17:51:51.176574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7b47ee06203'
down_revision = '11cf8bf6ec78'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracao_relatorio_formador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('tipo_periodo', sa.String(length=20), nullable=False),
    sa.Column('campos_relatorio', sa.JSON(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('fk_configuracao_relatorio_formador_cliente_id_cliente')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_configuracao_relatorio_formador'))
    )
    op.create_table('trilha_formativa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('fk_trilha_formativa_cliente_id_cliente')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trilha_formativa'))
    )
    op.create_table('arquivo_formador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('formador_id', sa.Integer(), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=255), nullable=False),
    sa.Column('nome_original', sa.String(length=255), nullable=False),
    sa.Column('caminho_arquivo', sa.String(length=500), nullable=False),
    sa.Column('frequencia_reenvio', sa.String(length=50), nullable=True),
    sa.Column('data_upload', sa.DateTime(), nullable=False),
    sa.Column('proximo_reenvio', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('fk_arquivo_formador_cliente_id_cliente')),
    sa.ForeignKeyConstraint(['formador_id'], ['ministrante.id'], name=op.f('fk_arquivo_formador_formador_id_ministrante')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_arquivo_formador'))
    )
    op.create_table('campo_trilha_formativa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trilha_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('obrigatorio', sa.Boolean(), nullable=True),
    sa.Column('opcoes', sa.Text(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['trilha_id'], ['trilha_formativa.id'], name=op.f('fk_campo_trilha_formativa_trilha_id_trilha_formativa')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campo_trilha_formativa'))
    )
    op.create_table('formador_monitor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('formador_id', sa.Integer(), nullable=False),
    sa.Column('monitor_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('data_associacao', sa.DateTime(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('fk_formador_monitor_cliente_id_cliente')),
    sa.ForeignKeyConstraint(['formador_id'], ['ministrante.id'], name=op.f('fk_formador_monitor_formador_id_ministrante')),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitor.id'], name=op.f('fk_formador_monitor_monitor_id_monitor')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_formador_monitor'))
    )
    op.create_table('resposta_trilha_formativa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trilha_id', sa.Integer(), nullable=False),
    sa.Column('formador_id', sa.Integer(), nullable=False),
    sa.Column('respostas', sa.JSON(), nullable=False),
    sa.Column('data_envio', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['formador_id'], ['ministrante.id'], name=op.f('fk_resposta_trilha_formativa_formador_id_ministrante')),
    sa.ForeignKeyConstraint(['trilha_id'], ['trilha_formativa.id'], name=op.f('fk_resposta_trilha_formativa_trilha_id_trilha_formativa')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resposta_trilha_formativa'))
    )
    op.create_table('relatorio_formador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('configuracao_id', sa.Integer(), nullable=False),
    sa.Column('formador_id', sa.Integer(), nullable=False),
    sa.Column('atividade_id', sa.Integer(), nullable=True),
    sa.Column('periodo_inicio', sa.Date(), nullable=True),
    sa.Column('periodo_fim', sa.Date(), nullable=True),
    sa.Column('dados_relatorio', sa.JSON(), nullable=False),
    sa.Column('data_envio', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['atividade_id'], ['oficina.id'], name=op.f('fk_relatorio_formador_atividade_id_oficina')),
    sa.ForeignKeyConstraint(['configuracao_id'], ['configuracao_relatorio_formador.id'], name=op.f('fk_relatorio_formador_configuracao_id_configuracao_relatorio_formador')),
    sa.ForeignKeyConstraint(['formador_id'], ['ministrante.id'], name=op.f('fk_relatorio_formador_formador_id_ministrante')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_relatorio_formador'))
    )
    op.create_table('solicitacao_material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('formador_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('atividade_id', sa.Integer(), nullable=True),
    sa.Column('tipo_solicitacao', sa.String(length=20), nullable=False),
    sa.Column('tipo_material', sa.String(length=255), nullable=False),
    sa.Column('unidade_medida', sa.String(length=50), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('justificativa', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('observacoes_cliente', sa.Text(), nullable=True),
    sa.Column('quantidade_aprovada', sa.Integer(), nullable=True),
    sa.Column('data_solicitacao', sa.DateTime(), nullable=False),
    sa.Column('data_resposta', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['atividade_id'], ['oficina.id'], name=op.f('fk_solicitacao_material_atividade_id_oficina')),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('fk_solicitacao_material_cliente_id_cliente')),
    sa.ForeignKeyConstraint(['formador_id'], ['ministrante.id'], name=op.f('fk_solicitacao_material_formador_id_ministrante')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_solicitacao_material'))
    )
    op.create_table('material_aprovado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitacao_id', sa.Integer(), nullable=False),
    sa.Column('monitor_id', sa.Integer(), nullable=True),
    sa.Column('quantidade_para_entrega', sa.Integer(), nullable=False),
    sa.Column('entregue', sa.Boolean(), nullable=True),
    sa.Column('data_entrega', sa.DateTime(), nullable=True),
    sa.Column('observacoes_entrega', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitor.id'], name=op.f('fk_material_aprovado_monitor_id_monitor')),
    sa.ForeignKeyConstraint(['solicitacao_id'], ['solicitacao_material.id'], name=op.f('fk_material_aprovado_solicitacao_id_solicitacao_material')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_material_aprovado'))
    )
    with op.batch_alter_table('ministrante', schema=None) as batch_op:
        existing_cols = {col['name'] for col in inspector.get_columns("ministrante")}
        existing_fks = {fk['name'] for fk in inspector.get_foreign_keys("ministrante")}
        if "telefone" not in existing_cols:
            batch_op.add_column(sa.Column('telefone', sa.String(length=20), nullable=True))
        if "endereco" not in existing_cols:
            batch_op.add_column(sa.Column('endereco', sa.String(length=500), nullable=True))
        if "banco" not in existing_cols:
            batch_op.add_column(sa.Column('banco', sa.String(length=100), nullable=True))
        if "agencia" not in existing_cols:
            batch_op.add_column(sa.Column('agencia', sa.String(length=20), nullable=True))
        if "conta" not in existing_cols:
            batch_op.add_column(sa.Column('conta', sa.String(length=30), nullable=True))
        if "tipo_conta" not in existing_cols:
            batch_op.add_column(sa.Column('tipo_conta', sa.String(length=20), nullable=True))
        if "chave_pix" not in existing_cols:
            batch_op.add_column(sa.Column('chave_pix', sa.String(length=255), nullable=True))
        if "ativo" not in existing_cols:
            batch_op.add_column(sa.Column('ativo', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ministrante', schema=None) as batch_op:
        existing_cols = {col['name'] for col in inspector.get_columns("ministrante")}
        existing_fks = {fk['name'] for fk in inspector.get_foreign_keys("ministrante")}
        batch_op.drop_column('ativo')
        batch_op.drop_column('chave_pix')
        batch_op.drop_column('tipo_conta')
        batch_op.drop_column('conta')
        batch_op.drop_column('agencia')
        batch_op.drop_column('banco')
        batch_op.drop_column('endereco')
        batch_op.drop_column('telefone')

    op.drop_table('material_aprovado')
    op.drop_table('solicitacao_material')
    op.drop_table('relatorio_formador')
    op.drop_table('resposta_trilha_formativa')
    op.drop_table('formador_monitor')
    op.drop_table('campo_trilha_formativa')
    op.drop_table('arquivo_formador')
    op.drop_table('trilha_formativa')
    op.drop_table('configuracao_relatorio_formador')
    # ### end Alembic commands ###
