"""empty message

Revision ID: ced4f6bf8596
Revises: 
Create Date: 2025-04-16 17:04:13.167470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ced4f6bf8596'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback_campo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cliente_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_feedback_campo_cliente_id_cliente',
            'cliente', ['cliente_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback_campo', schema=None) as batch_op:
        batch_op.drop_constraint(
            'fk_feedback_campo_cliente_id_cliente',
            type_='foreignkey'
        )
        batch_op.drop_column('cliente_id')

    # ### end Alembic commands ###
