"""Add limite_total_revisores to ConfiguracaoCliente

Revision ID: d4889a23ebd8
Revises: 13fb46fe90bf
Create Date: 2025-08-28 17:08:31.715768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4889a23ebd8'
down_revision = '13fb46fe90bf'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('revisor_process_evento')
    with op.batch_alter_table('configuracao_cliente', schema=None) as batch_op:
        existing_cols = {col['name'] for col in inspector.get_columns("configuracao_cliente")}
        existing_fks = {fk['name'] for fk in inspector.get_foreign_keys("configuracao_cliente")}
        if "limite_total_revisores" not in existing_cols:
            batch_op.add_column(sa.Column('limite_total_revisores', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracao_cliente', schema=None) as batch_op:
        existing_cols = {col['name'] for col in inspector.get_columns("configuracao_cliente")}
        existing_fks = {fk['name'] for fk in inspector.get_foreign_keys("configuracao_cliente")}
        batch_op.drop_column('limite_total_revisores')

    op.create_table('revisor_process_evento',
    sa.Column('process_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('evento_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id'], name='fk_revisor_process_evento_evento_id_evento'),
    sa.ForeignKeyConstraint(['process_id'], ['revisor_process.id'], name='fk_revisor_process_evento_process_id_revisor_process'),
    sa.PrimaryKeyConstraint('process_id', 'evento_id', name='pk_revisor_process_evento')
    )
    # ### end Alembic commands ###
