"""Add InscricaoEvento model

Revision ID: d696cddcb68a
Revises: ec49f496ccef
Create Date: 2025-04-02 15:26:25.520336

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd696cddcb68a'
down_revision = 'ec49f496ccef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inscricao_evento')
    with op.batch_alter_table('inscricao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_inscricao_evento_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'evento_inscricao_tipo', ['tipo_inscricao_evento_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscricao', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tipo_inscricao_evento_id')

    op.create_table('inscricao_evento',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('evento_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo_inscricao_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data_inscricao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id'], name='inscricao_evento_evento_id_fkey'),
    sa.ForeignKeyConstraint(['tipo_inscricao_id'], ['inscricao_tipo.id'], name='inscricao_evento_tipo_inscricao_id_fkey'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name='inscricao_evento_usuario_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='inscricao_evento_pkey')
    )
    # ### end Alembic commands ###
