"""initial migration

Revision ID: d850a0eed234
Revises: 9a2b6411ecbe
Create Date: 2025-04-13 17:13:40.687410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd850a0eed234'
down_revision = '9a2b6411ecbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('habilitar_lotes', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.drop_column('habilitar_lotes')

    # ### end Alembic commands ###
