"""Add MaterialDisponivel and SolicitacaoMaterialFormador tables

Revision ID: d8e9f1a2b3c4
Revises: c7b47ee06203
Create Date: 2025-01-28 15:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd8e9f1a2b3c4'
down_revision = 'c7b47ee06203'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create MaterialDisponivel table
    op.create_table('material_disponivel',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('material_id', sa.Integer(), nullable=False),
        sa.Column('cliente_id', sa.Integer(), nullable=False),
        sa.Column('quantidade_minima', sa.Integer(), nullable=False, server_default='1'),
        sa.Column('quantidade_maxima', sa.Integer(), nullable=False, server_default='100'),
        sa.Column('controle_estoque', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('ativo', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['material_id'], ['material.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create SolicitacaoMaterialFormador table
    op.create_table('solicitacao_material_formador',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('formador_id', sa.Integer(), nullable=False),
        sa.Column('cliente_id', sa.Integer(), nullable=False),
        sa.Column('tipo_solicitacao', sa.String(20), nullable=False, server_default='existente'),
        sa.Column('material_disponivel_id', sa.Integer(), nullable=True),
        sa.Column('nome_material', sa.String(200), nullable=True),
        sa.Column('descricao_material', sa.Text(), nullable=True),
        sa.Column('unidade_medida', sa.String(50), nullable=True),
        sa.Column('quantidade_solicitada', sa.Integer(), nullable=False),
        sa.Column('justificativa', sa.Text(), nullable=True),
        sa.Column('status', sa.String(20), nullable=False, server_default='pendente'),
        sa.Column('quantidade_aprovada', sa.Integer(), nullable=True),
        sa.Column('observacoes_cliente', sa.Text(), nullable=True),
        sa.Column('entregue', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('data_entrega', sa.DateTime(), nullable=True),
        sa.Column('observacoes_entrega', sa.Text(), nullable=True),
        sa.Column('data_solicitacao', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.Column('data_resposta', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['formador_id'], ['ministrante.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['material_disponivel_id'], ['material_disponivel.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create indexes for better performance
    op.create_index('ix_material_disponivel_cliente_id', 'material_disponivel', ['cliente_id'])
    op.create_index('ix_material_disponivel_material_id', 'material_disponivel', ['material_id'])
    op.create_index('ix_solicitacao_material_formador_formador_id', 'solicitacao_material_formador', ['formador_id'])
    op.create_index('ix_solicitacao_material_formador_cliente_id', 'solicitacao_material_formador', ['cliente_id'])
    op.create_index('ix_solicitacao_material_formador_status', 'solicitacao_material_formador', ['status'])
    op.create_index('ix_solicitacao_material_formador_data_solicitacao', 'solicitacao_material_formador', ['data_solicitacao'])
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop indexes
    op.drop_index('ix_solicitacao_material_formador_data_solicitacao', 'solicitacao_material_formador')
    op.drop_index('ix_solicitacao_material_formador_status', 'solicitacao_material_formador')
    op.drop_index('ix_solicitacao_material_formador_cliente_id', 'solicitacao_material_formador')
    op.drop_index('ix_solicitacao_material_formador_formador_id', 'solicitacao_material_formador')
    op.drop_index('ix_material_disponivel_material_id', 'material_disponivel')
    op.drop_index('ix_material_disponivel_cliente_id', 'material_disponivel')
    
    # Drop tables
    op.drop_table('solicitacao_material_formador')
    op.drop_table('material_disponivel')
    
    # ### end Alembic commands ###