"""campos evento faltando

Revision ID: d9b1cbc8255f
Revises: f85d31411ef1
Create Date: 2025-03-17 15:44:48.789094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9b1cbc8255f'
down_revision = 'f85d31411ef1'
branch_labels = None
depends_on = None


def upgrade():
    # Primeiro adicione a coluna com valor padrão, permitindo NULL temporariamente
    op.add_column('evento', sa.Column('capacidade_padrao', sa.Integer(), nullable=True))
    
    # Atualize os registros existentes com um valor padrão (por exemplo, 10)
    op.execute("UPDATE evento SET capacidade_padrao = 10")
    
    # Agora altere a coluna para NOT NULL
    op.alter_column('evento', 'capacidade_padrao', nullable=False)
    
    # Faça o mesmo para as outras colunas
    op.add_column('evento', sa.Column('requer_aprovacao', sa.Boolean(), nullable=True))
    op.execute("UPDATE evento SET requer_aprovacao = FALSE")
    op.alter_column('evento', 'requer_aprovacao', nullable=False)
    
    op.add_column('evento', sa.Column('publico', sa.Boolean(), nullable=True))
    op.execute("UPDATE evento SET publico = TRUE")
    op.alter_column('evento', 'publico', nullable=False)
    
    

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.drop_column('publico')
        batch_op.drop_column('requer_aprovacao')
        batch_op.drop_column('capacidade_padrao')

    # ### end Alembic commands ###
