"""Nova migração inicial

Revision ID: da033b403a2d
Revises: 
Create Date: 2025-02-24 14:41:52.921253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da033b403a2d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ministrante_id', sa.Integer(), nullable=True))
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'ministrante', ['ministrante_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('ministrante_id')

    # ### end Alembic commands ###
