"""relatorio material ministrante atualizado com m tipo oficina 

Revision ID: da683a744662
Revises: 4a423c99fb29
Create Date: 2025-02-06 11:01:51.317096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da683a744662'
down_revision = '4a423c99fb29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
