"""ajuste_checkin

Revision ID: dc6bca8eba59
Revises: f19c5a40e84a
Create Date: 2025-04-03 16:47:36.981495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc6bca8eba59'
down_revision = 'f19c5a40e84a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('evento_id', sa.Integer(), nullable=True))
        batch_op.alter_column('oficina_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'evento', ['evento_id'], ['id'])

    with op.batch_alter_table('configuracao_cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('habilitar_qrcode_evento_credenciamento', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracao_cliente', schema=None) as batch_op:
        batch_op.drop_column('habilitar_qrcode_evento_credenciamento')

    with op.batch_alter_table('checkin', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('oficina_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('evento_id')

    # ### end Alembic commands ###
