"""empty message

Revision ID: df333753e4c7
Revises: b028d7157f10
Create Date: 2025-09-12 16:31:16.222072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df333753e4c7'
down_revision = 'b028d7157f10'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campos_formulario', schema=None) as batch_op:
        existing_cols = {col['name'] for col in inspector.get_columns("campos_formulario")}
        existing_fks = {fk['name'] for fk in inspector.get_foreign_keys("campos_formulario")}
        if "ordem" not in existing_cols:
            batch_op.add_column(sa.Column('ordem', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campos_formulario', schema=None) as batch_op:
        existing_cols = {col['name'] for col in inspector.get_columns("campos_formulario")}
        existing_fks = {fk['name'] for fk in inspector.get_foreign_keys("campos_formulario")}
        batch_op.drop_column('ordem')

    # ### end Alembic commands ###
