"""Add nome_revisor field to avaliacao_barema table

Revision ID: df5ad5e5fe2f
Revises: ca04cbd5db16
Create Date: 2025-09-22 16:55:54.084765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df5ad5e5fe2f'
down_revision = 'ca04cbd5db16'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avaliacao_barema', schema=None) as batch_op:
        existing_cols = {col['name'] for col in inspector.get_columns("avaliacao_barema")}
        existing_fks = {fk['name'] for fk in inspector.get_foreign_keys("avaliacao_barema")}
        if "nome_revisor" not in existing_cols:
            batch_op.add_column(sa.Column('nome_revisor', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avaliacao_barema', schema=None) as batch_op:
        existing_cols = {col['name'] for col in inspector.get_columns("avaliacao_barema")}
        existing_fks = {fk['name'] for fk in inspector.get_foreign_keys("avaliacao_barema")}
        batch_op.drop_column('nome_revisor')

    # ### end Alembic commands ###
