"""empty message

Revision ID: dfb0186af775
Revises: f09857675d5a
Create Date: 2025-09-03 01:13:57.682443

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dfb0186af775'
down_revision = 'f09857675d5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_distribution_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('total_submissions', sa.Integer(), nullable=False),
    sa.Column('total_assignments', sa.Integer(), nullable=False),
    sa.Column('distribution_seed', sa.String(length=50), nullable=True),
    sa.Column('conflicts_detected', sa.Integer(), nullable=True),
    sa.Column('fallback_assignments', sa.Integer(), nullable=True),
    sa.Column('failed_assignments', sa.Integer(), nullable=True),
    sa.Column('distribution_details', sa.JSON(), nullable=True),
    sa.Column('error_log', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id'], name=op.f('fk_auto_distribution_log_evento_id_evento')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auto_distribution_log'))
    )
    op.drop_table('distribution_log')
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resposta_formulario_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('distribution_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('distribution_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('distributed_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.drop_constraint('fk_assignment_submission_id_submission', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_assignment_resposta_formulario_id_respostas_formulario'), 'respostas_formulario', ['resposta_formulario_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_assignment_distributed_by_usuario'), 'usuario', ['distributed_by'], ['id'])
        batch_op.drop_column('submission_id')

    with op.batch_alter_table('respostas_formulario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trabalho_id', sa.Integer(), nullable=True))
        batch_op.alter_column('formulario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(batch_op.f('fk_respostas_formulario_trabalho_id_submission'), 'submission', ['trabalho_id'], ['id'])

    with op.batch_alter_table('revisor_process', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('descricao', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('revisor_process', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('descricao')
        batch_op.drop_column('nome')

    with op.batch_alter_table('respostas_formulario', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_respostas_formulario_trabalho_id_submission'), type_='foreignkey')
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('formulario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('trabalho_id')

    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submission_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_assignment_distributed_by_usuario'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_assignment_resposta_formulario_id_respostas_formulario'), type_='foreignkey')
        batch_op.create_foreign_key('fk_assignment_submission_id_submission', 'submission', ['submission_id'], ['id'])
        batch_op.drop_column('notes')
        batch_op.drop_column('distributed_by')
        batch_op.drop_column('distribution_date')
        batch_op.drop_column('distribution_type')
        batch_op.drop_column('resposta_formulario_id')

    op.create_table('distribution_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('evento_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_submissions', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_assignments', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('distribution_seed', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('conflicts_detected', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fallback_assignments', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('failed_assignments', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('distribution_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error_log', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('duration_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id'], name='fk_distribution_log_evento_id_evento'),
    sa.PrimaryKeyConstraint('id', name='pk_distribution_log')
    )
    op.drop_table('auto_distribution_log')
    # ### end Alembic commands ###
