"""add index status_pagamento

Revision ID: e088bd8f30ca
Revises: 
Create Date: 2025-04-10 22:10:10.224327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e088bd8f30ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscricao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inscricao_status_pagamento'), ['status_pagamento'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscricao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inscricao_status_pagamento'))

    # ### end Alembic commands ###
