"""Add motivo_recusa field to AgendamentoVisita model

Revision ID: e10db5af1c00
Revises: 1e6c5277571b
Create Date: 2025-08-27 00:32:16.544537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e10db5af1c00'
down_revision = '1e6c5277571b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamento_visita', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motivo_recusa', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamento_visita', schema=None) as batch_op:
        batch_op.drop_column('motivo_recusa')

    # ### end Alembic commands ###
