"""Add motivo_recusa field to AgendamentoVisita model

Revision ID: e10db5af1c00
Revises: 1e6c5277571b
Create Date: 2025-08-27 00:32:16.544537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e10db5af1c00'
down_revision = '1e6c5277571b'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamento_visita', schema=None) as batch_op:
        existing_cols = {col['name'] for col in inspector.get_columns("agendamento_visita")}
        existing_fks = {fk['name'] for fk in inspector.get_foreign_keys("agendamento_visita")}
        if "motivo_recusa" not in existing_cols:
            batch_op.add_column(sa.Column('motivo_recusa', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamento_visita', schema=None) as batch_op:
        existing_cols = {col['name'] for col in inspector.get_columns("agendamento_visita")}
        existing_fks = {fk['name'] for fk in inspector.get_foreign_keys("agendamento_visita")}
        batch_op.drop_column('motivo_recusa')

    # ### end Alembic commands ###
