"""Adicionando campo habilitar_feedback na tabela Configuracao relatorio ministranteATUALIZANDOCOMERRO

Revision ID: e1df3e7726a0
Revises: f0caaef924c8
Create Date: 2025-02-06 18:30:38.931481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1df3e7726a0'
down_revision = 'f0caaef924c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
