"""empty message

Revision ID: e496c12490c7
Revises: 931a82d6224c
Create Date: 2025-09-16 12:46:05.728028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e496c12490c7'
down_revision = '931a82d6224c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formador_polo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('formador_id', sa.Integer(), nullable=False),
    sa.Column('polo_id', sa.Integer(), nullable=False),
    sa.Column('data_atribuicao', sa.DateTime(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['formador_id'], ['ministrante.id'], name=op.f('fk_formador_polo_formador_id_ministrante')),
    sa.ForeignKeyConstraint(['polo_id'], ['polo.id'], name=op.f('fk_formador_polo_polo_id_polo')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_formador_polo'))
    )
    with op.batch_alter_table('solicitacao_material_formador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacao_material_formador', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    op.drop_table('formador_polo')
    # ### end Alembic commands ###
