"""Adicionar tipo_inscricao_id à tabela usuario

Revision ID: e5166b6ff4b2
Revises: 279a45daec4e
Create Date: 2025-04-02 11:28:43.249954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5166b6ff4b2'
down_revision = '279a45daec4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint('usuario_tipo_inscricao_id_fkey', type_='foreignkey')
        batch_op.drop_column('tipo_inscricao_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_inscricao_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('usuario_tipo_inscricao_id_fkey', 'evento_inscricao_tipo', ['tipo_inscricao_id'], ['id'])

    # ### end Alembic commands ###
