"""Recriando estrutura do banco

Revision ID: e8249eb9ca71
Revises: dc6bca8eba59
Create Date: 2025-04-05 11:56:23.163304
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e8249eb9ca71'
down_revision = 'dc6bca8eba59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkin', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('evento_id', sa.Integer(), nullable=True))
        batch_op.alter_column('oficina_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        # batch_op.create_foreign_key(None, 'evento', ['evento_id'], ['id'])
        pass  # evita erro de identação se todas as linhas estiverem comentadas

    with op.batch_alter_table('configuracao_cliente', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('habilitar_qrcode_evento_credenciamento', sa.Boolean(), nullable=True))
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracao_cliente', schema=None) as batch_op:
        # batch_op.drop_column('habilitar_qrcode_evento_credenciamento')
        pass

    with op.batch_alter_table('checkin', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('oficina_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        # batch_op.drop_column('evento_id')
        pass

    # ### end Alembic commands ###
