"""Add tipo_necessidade_especial and descricao_necessidade_especial to aluno_visitante

Revision ID: e89dc0a9d598
Revises: 8bfe3fda20ef
Create Date: 2025-08-31 13:19:58.145753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e89dc0a9d598'
down_revision = '8bfe3fda20ef'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    # ### commands auto generated by Alembic - please adjust! ###
    existing_cols = {col['name'] for col in inspector.get_columns("aluno_visitante")}
    if "tipo_necessidade_especial" not in existing_cols:
        op.add_column('aluno_visitante', sa.Column('tipo_necessidade_especial', sa.String(length=100), nullable=True))
    existing_cols = {col['name'] for col in inspector.get_columns("aluno_visitante")}
    if "descricao_necessidade_especial" not in existing_cols:
        op.add_column('aluno_visitante', sa.Column('descricao_necessidade_especial', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aluno_visitante', 'descricao_necessidade_especial')
    op.drop_column('aluno_visitante', 'tipo_necessidade_especial')
    # ### end Alembic commands ###
