"""Add InscricaoEvento model

Revision ID: ec49f496ccef
Revises: e5166b6ff4b2
Create Date: 2025-04-02 14:12:30.249402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec49f496ccef'
down_revision = 'e5166b6ff4b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscricao_evento', schema=None) as batch_op:
        batch_op.drop_constraint('inscricao_evento_tipo_inscricao_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'inscricao_tipo', ['tipo_inscricao_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscricao_evento', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('inscricao_evento_tipo_inscricao_id_fkey', 'evento_inscricao_tipo', ['tipo_inscricao_id'], ['id'])

    # ### end Alembic commands ###
