"""Adicionando campo habilitar_feedback na tabela Configuracao relatorio ministrante

Revision ID: f0caaef924c8
Revises: da683a744662
Create Date: 2025-02-06 18:23:52.385989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0caaef924c8'
down_revision = 'da683a744662'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
