"""rename disponibilidade columns

Revision ID: f6c95551a473
Revises: 4717ce6a525e
Create Date: 2025-07-01 00:54:43.019457

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f6c95551a473'
down_revision = '4717ce6a525e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamento_visita', schema=None) as batch_op:
        batch_op.drop_constraint('agendamento_visita_qr_code_token_key', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_agendamento_visita_qr_code_token'), ['qr_code_token'])

    with op.batch_alter_table('revisor_process', schema=None) as batch_op:
        batch_op.drop_column('titulo')
        batch_op.drop_column('data_fim')
        batch_op.drop_column('data_inicio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('revisor_process', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_inicio', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('data_fim', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('titulo', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    with op.batch_alter_table('agendamento_visita', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_agendamento_visita_qr_code_token'), type_='unique')
        batch_op.create_unique_constraint('agendamento_visita_qr_code_token_key', ['qr_code_token'])

    # ### end Alembic commands ###
