"""vamos la

Revision ID: f7d5ebd9f9ed
Revises: 6e4b996d6686
Create Date: 2025-02-20 15:09:25.863660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7d5ebd9f9ed'
down_revision = '6e4b996d6686'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oficina', schema=None) as batch_op:
        batch_op.drop_column('observacao')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oficina', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observacao', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
