"""empty message

Revision ID: f9c0151dcad9
Revises: 1334695f7e0a
Create Date: 2025-09-29 20:31:03.438871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9c0151dcad9'
down_revision = '1334695f7e0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificado_revisor_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('incluir_assinatura_cliente', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificado_revisor_config', schema=None) as batch_op:
        batch_op.drop_column('incluir_assinatura_cliente')

    # ### end Alembic commands ###
