"""status_pagamento

Revision ID: fba49bb928d0
Revises: 284d77f90e08
Create Date: 2025-04-10 11:31:07.184447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fba49bb928d0'
down_revision = '284d77f90e08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscricao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_pagamento', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscricao', schema=None) as batch_op:
        batch_op.drop_column('status_pagamento')

    # ### end Alembic commands ###
