"""Recriando estrutura do banco

Revision ID: fcb3c49a8165
Revises: 
Create Date: 2025-03-15 10:51:08.483249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcb3c49a8165'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ministrante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categorias_formacao', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('foto', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ministrante', schema=None) as batch_op:
        batch_op.drop_column('foto')
        batch_op.drop_column('categorias_formacao')

    # ### end Alembic commands ###
