"""teste sync

Revision ID: ffbc68259c84
Revises: 2b55b8a15aaf
Create Date: 2025-06-25 01:11:45.422474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffbc68259c84'
down_revision = '2b55b8a15aaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamento_visita', schema=None) as batch_op:
        batch_op.drop_constraint('agendamento_visita_qr_code_token_key', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_agendamento_visita_qr_code_token'), ['qr_code_token'])

    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_constraint('cliente_email_key', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_cliente_email'), ['email'])

    with op.batch_alter_table('inscricao', schema=None) as batch_op:
        batch_op.drop_constraint('inscricao_qr_code_token_key', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_inscricao_qr_code_token'), ['qr_code_token'])

    with op.batch_alter_table('link_cadastro', schema=None) as batch_op:
        batch_op.drop_constraint('link_cadastro_slug_customizado_key', type_='unique')
        batch_op.drop_constraint('link_cadastro_token_key', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_link_cadastro_slug_customizado'), ['slug_customizado'])
        batch_op.create_unique_constraint(batch_op.f('uq_link_cadastro_token'), ['token'])

    with op.batch_alter_table('ministrante', schema=None) as batch_op:
        batch_op.drop_constraint('ministrante_cpf_key', type_='unique')
        batch_op.drop_constraint('ministrante_email_key', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_ministrante_cpf'), ['cpf'])
        batch_op.create_unique_constraint(batch_op.f('uq_ministrante_email'), ['email'])

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint('review_locator_key', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_review_locator'), ['locator'])

    with op.batch_alter_table('revisao_config', schema=None) as batch_op:
        batch_op.drop_constraint('revisao_config_evento_id_key', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_revisao_config_evento_id'), ['evento_id'])

    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.drop_constraint('submission_locator_key', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_submission_locator'), ['locator'])

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ativo', sa.Boolean(), nullable=True))
        batch_op.drop_constraint('usuario_cpf_key', type_='unique')
        batch_op.drop_constraint('usuario_email_key', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_usuario_cpf'), ['cpf'])
        batch_op.create_unique_constraint(batch_op.f('uq_usuario_email'), ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_usuario_email'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_usuario_cpf'), type_='unique')
        batch_op.create_unique_constraint('usuario_email_key', ['email'])
        batch_op.create_unique_constraint('usuario_cpf_key', ['cpf'])
        batch_op.drop_column('ativo')

    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_submission_locator'), type_='unique')
        batch_op.create_unique_constraint('submission_locator_key', ['locator'])

    with op.batch_alter_table('revisao_config', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_revisao_config_evento_id'), type_='unique')
        batch_op.create_unique_constraint('revisao_config_evento_id_key', ['evento_id'])

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_review_locator'), type_='unique')
        batch_op.create_unique_constraint('review_locator_key', ['locator'])

    with op.batch_alter_table('ministrante', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_ministrante_email'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_ministrante_cpf'), type_='unique')
        batch_op.create_unique_constraint('ministrante_email_key', ['email'])
        batch_op.create_unique_constraint('ministrante_cpf_key', ['cpf'])

    with op.batch_alter_table('link_cadastro', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_link_cadastro_token'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_link_cadastro_slug_customizado'), type_='unique')
        batch_op.create_unique_constraint('link_cadastro_token_key', ['token'])
        batch_op.create_unique_constraint('link_cadastro_slug_customizado_key', ['slug_customizado'])

    with op.batch_alter_table('inscricao', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_inscricao_qr_code_token'), type_='unique')
        batch_op.create_unique_constraint('inscricao_qr_code_token_key', ['qr_code_token'])

    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_cliente_email'), type_='unique')
        batch_op.create_unique_constraint('cliente_email_key', ['email'])

    with op.batch_alter_table('agendamento_visita', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_agendamento_visita_qr_code_token'), type_='unique')
        batch_op.create_unique_constraint('agendamento_visita_qr_code_token_key', ['qr_code_token'])

    # ### end Alembic commands ###
